/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.train.cleanning;

import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import parabitparis.PbtDbConn;

/**
 *
 * @author HP
 */
public class TrainCleanningMain1 extends javax.swing.JDialog implements Runnable {

    /**
     * Creates new form TrainCleanningMain1
     */
     boolean b=true;
    Thread th;
    PbtDbConn mycon1,mycon2,mycon3,mycon4;
    String str,tn;
    DefaultTableModel dtm1;
    public TrainCleanningMain1(java.awt.Frame parent, boolean modal,String ss) {
        super(parent, modal);
        initComponents();
        setIconImage();
        this.setBounds(265,170,805,480);
        jButton1.setOpaque(false);
     jButton1.setContentAreaFilled(false);
     jButton1.setBorderPainted(false);
     jButton2.setOpaque(false);
     jButton2.setContentAreaFilled(false);
     jButton2.setBorderPainted(false);
     jButton3.setOpaque(false);
     jButton3.setContentAreaFilled(false);
     jButton3.setBorderPainted(false);
  //   jButton4.setOpaque(false);
    // jButton4.setContentAreaFilled(false);
   //  jButton4.setBorderPainted(false);
         tn=ss;
     th=new Thread(this);
       mycon1=new PbtDbConn();
        mycon2=new PbtDbConn();
        mycon3=new PbtDbConn();
        mycon4=new PbtDbConn();
        
       dtm1=(DefaultTableModel)jTable1.getModel();
       dtm1.setColumnCount(4);
       //dtm1.setColumnIdentifiers(new Object[]{"PNR","Seat No","Coach","Problem"});
       str="select a.PNR,a.Seat,a.Coach,a.PrId,b.Problem from rtproblem a,problemrt b where a.Status='N' and a.PrID=b.PrID and ((b.PrID='PR 5')or(b.PrID='PR 6')or(b.PrID='PR 25')or(b.PrID='PR 26')or(b.PrID='PR 27'))";
      try{
       mycon1.rs=mycon1.stm.executeQuery(str);
       dtm1.setRowCount(0);
       while(mycon1.rs.next())
       {
           mycon1.rs.getString("a.PrID");
            mycon1.rs.getString("a.PNR");
            mycon1.rs.getString("a.Seat");
            mycon1.rs.getString("a.Coach");
            mycon1.rs.getString("b.Problem"); 
            dtm1.addRow(new Object[]{mycon1.rs.getString("a.PNR"), mycon1.rs.getString("a.Seat"),mycon1.rs.getString("a.Coach"),mycon1.rs.getString("b.Problem")});
            }
       jTable1.setModel(dtm1);
      }catch(SQLException e){
//          e.printStackTrace();
      }
      th.start();
    }
    public void run()
{
System.out.println(str);
while(b){
    System.out.println(str);
      try{
       mycon1.rs=mycon1.stm.executeQuery(str);
       dtm1.setRowCount(0);
       while(mycon1.rs.next())
       {
            dtm1.addRow(new Object[]{mycon1.rs.getString("a.PNR"), mycon1.rs.getString("a.Seat"),mycon1.rs.getString("a.Coach"),mycon1.rs.getString("b.Problem")});
            }
       
       jTable1.setModel(dtm1);
       
      th.sleep(15000);
      }catch(Exception e){
//          e.printStackTrace();
      }
    }
 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PNR", "Seat No", "Coach", "Problem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 50, 680, 300);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("CLEANNING :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(36, 12, 120, 30);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\ICONS\\back-button1.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 370, 40, 30);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\solved1.jpg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 370, 120, 40);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\Pass.jpg")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(560, 370, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\20 gradi\\photo-1508796079212-a4b83cbf734d.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 810, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        th.stop();
        this.dispose();        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                dtm1.getValueAt(jTable1.getSelectedRow(),0);
        String rt="update rtproblem a,problemrt b set a.status='S' where a.PNR='"+dtm1.getValueAt(jTable1.getSelectedRow(),0)+"'and a.PrID=b.PrID and b.Problem='"+dtm1.getValueAt(jTable1.getSelectedRow(),3)+"' and a.coach='"+dtm1.getValueAt(jTable1.getSelectedRow(),2)+"'";
        System.out.println(rt);
        try{
           mycon2.stm.executeUpdate(rt);
        }   catch(SQLException e){
            JOptionPane.showMessageDialog(null,"PLEASE SELECT");
//            e.printStackTrace();
        }         
                dtm1.removeRow(jTable1.getSelectedRow());
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                String sno="",sid="",stop="",sno1="",rid="",ud="",scat="";
        dtm1.getValueAt(jTable1.getSelectedRow(), 0);
       String ro="select UD from troute where TrNo='"+tn+"'";
        System.out.println(ro);
      /* String uu="select SNo,PrevSID from currentstatus where TrNo='"+tn+"'";
        System.out.println(uu);
        String w="select a.SID,a.Stop,a.SNo,b.RID,c.SCat from rstdetail a,troute b,station c where b.TrNo='"+tn+"' and a.SNo>'"+sno+"' and a.RID=b.RID and c.SID=a.SID group by SNo";
        System.out.println(w);
        String w1="select a.SID,a.Stop,a.SNo,b.RID,c.SCat from rstdetail a,troute b,station c where b.TrNo='"+tn+"' and a.SNo<'"+sno+"' and a.RID=b.RID and c.SID=a.SID group by SNo";
        System.out.println(w1);
        String g="update rtproblem a,problemrt b set a.Status='PS-'"+sid+"where a.PNR='"+dtm1.getValueAt(jTable1.getSelectedRow(),0)+" 'and a.PrID=b.PrID and b.Problem='"+dtm1.getValueAt(jTable1.getSelectedRow(),3)+"' and a.coach='"+dtm1.getValueAt(jTable1.getSelectedRow(),2)+"'";
            System.out.println(g);*/
            try{
                mycon1.rs=mycon1.stm.executeQuery(ro);
                if(mycon1.rs.next()){
                   ud=mycon1.rs.getString("UD");
                }
               if(ud.equals("u")){
                   String uu="select SNo,PrevSID from currentstatus where TrNo='"+tn+"'";
        System.out.println(uu);
                   mycon4.rs=mycon4.stm.executeQuery(uu);
               if( mycon4.rs.next()){
                    sno=mycon4.rs.getString("SNo");
               }
                String w="select a.SID,a.Stop,a.SNo,b.RID,c.SCat from rstdetail a,troute b,station c where b.TrNo='"+tn+"' and a.SNo>'"+sno+"' and a.RID=b.RID and c.SID=a.SID group by SNo";
        System.out.println(w);
                   mycon1.rs=mycon1.stm.executeQuery(w);
                   while(mycon1.rs.next()){
                   mycon1.rs.getString("a.SID");
                   mycon1.rs.getString("a.Stop");
                   mycon1.rs.getString("a.SNo");
                   mycon1.rs.getString("b.RID");
                   mycon1.rs.getString("c.SCat");
                   if((mycon1.rs.getString("c.SCat").equals("A")||mycon1.rs.getString("c.SCat").equals("B")||mycon1.rs.getString("c.SCat").equals("C"))&&(mycon1.rs.getString("a.Stop").equals("Y"))){
                   sid= mycon1.rs.getString("a.SID");
                   stop= mycon1.rs.getString("a.Stop");
                   sno1= mycon1.rs.getString("a.SNo");
                   rid=mycon1.rs.getString("b.RID");
                   scat=mycon1.rs.getString("c.SCat");
                   break;
                   } 
                   }
               }
               else{
                   String uu="select SNo,PrevSID from currentstatus where TrNo='"+tn+"'";
        System.out.println(uu);
                 mycon4.rs=mycon4.stm.executeQuery(uu);
                if(mycon4.rs.next()){
                    sno=mycon4.rs.getString("SNo");
                }
                String w1="select a.SID,a.Stop,a.SNo,b.RID,c.SCat from rstdetail a,troute b,station c where b.TrNo='"+tn+"' and a.SNo<'"+sno+"' and a.RID=b.RID and c.SID=a.SID group by SNo";
        System.out.println(w1);
                mycon1.rs=mycon1.stm.executeQuery(w1); 
               while(mycon1.rs.previous()){
                   mycon1.rs.getString("a.SID");
                   mycon1.rs.getString("a.Stop");
                   mycon1.rs.getString("a.SNo");
                   mycon1.rs.getString("b.RID");
                   mycon1.rs.getString("c.SCat");
                   if((mycon1.rs.getString("c.SCat").equals("A")||mycon1.rs.getString("c.SCat").equals("B")||mycon1.rs.getString("c.SCat").equals("C"))&&(mycon1.rs.getString("a.Stop").equals("Y"))){
                   sid= mycon1.rs.getString("a.SID");
                   stop= mycon1.rs.getString("a.Stop");
                   sno1= mycon1.rs.getString("a.SNo");
                   rid=mycon1.rs.getString("b.RID");
                   scat=mycon1.rs.getString("c.SCat");
                   break;
                   } 
                   }
               }
               String g="update rtproblem a,problemrt b set a.Status='PS-"+sid+"'where a.PNR='"+dtm1.getValueAt(jTable1.getSelectedRow(),0)+" 'and a.PrID=b.PrID and b.Problem='"+dtm1.getValueAt(jTable1.getSelectedRow(),3)+"' and a.coach='"+dtm1.getValueAt(jTable1.getSelectedRow(),2)+"'";
            System.out.println(g);
               mycon3.stm.executeUpdate(g);
                
            }catch(SQLException e)
            {   
                JOptionPane.showMessageDialog(null,"PLEASE SELECT");
//                e.printStackTrace();
        }
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("FLAG22.png")));
    }

}
