/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.authority;

import javax.swing.table.DefaultTableModel;
import parabitparis.PbtDbConn;

/**
 *
 * @author HP
 */
public class GeneralManager extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form RHead
     */
    Object dname;
    String str,str2,str3;
    Boolean b=true;
    DefaultTableModel dtm1;
    PbtDbConn mycon1,mycon2;
    int zid;
    Thread th;
    public GeneralManager(int zid) {
        this.setUndecorated(true);
        initComponents();
        mycon1=new PbtDbConn();
        mycon2=new PbtDbConn();
        this.setBounds(240,150,880,520);
        jButton1.setOpaque(false);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        this.zid=zid;
        dtm1=(DefaultTableModel)jTable1.getModel();
        dtm1.setRowCount(0);
         str="select DID from division where ZID='"+zid+"'";
         System.out.println(str);
        try{
        mycon1.rs=mycon1.stm.executeQuery(str);
        while(mycon1.rs.next())
        {
         str2="select a.PNR,a.Count,b.Problem,c.TrNo,d.DID from rtproblem a, problemrt b, ps c,division d where a.Status='"+mycon1.rs.getString("DID")+"' and a.PrID=b.PrID and c.PNR=a.PNR group by a.PrID";
         System.out.println(str2);
         mycon2.rs=mycon2.stm.executeQuery(str2);
        while(mycon2.rs.next())
        {
         str3="select DName from division where DID='"+mycon2.rs.getString("d.DID")+"'";
         System.out.println(str3);
         mycon1.rs=mycon1.stm.executeQuery(str3);
        if(mycon1.rs.next())
        {
            dname=mycon1.rs.getString("DName");
        
        }
        dtm1.addRow(new Object[]{mycon2.rs.getString("c.TrNo"),mycon2.rs.getString("a.PNR"),mycon2.rs.getString("b.Problem"),mycon2.rs.getString("a.Count"),mycon1.rs.getString("DName")});
        }
        jTable1.setModel(dtm1);
        }
        }catch(Exception e)
        {
        e.printStackTrace();
        }
        th=new Thread(this);
        th.start();
    }
    
    
    public void run()
    {
    while(b)
    {
        
          str="select DID from division where zid='"+zid+"'";
          System.out.println(str);
          try{
            th.sleep(15000);
            dtm1.setRowCount(0);
        mycon1.rs=mycon1.stm.executeQuery(str);
        while(mycon1.rs.next())
        {
         str2="select a.PNR,a.Count,b.Problem,c.TrNo,d.DID from rtproblem a, problemrt b, ps c,division d where a.Status='"+mycon1.rs.getString("DID")+"' and a.PrID=b.PrID and c.PNR=a.PNR group by a.PrID";
         System.out.println(str2);
         mycon2.rs=mycon2.stm.executeQuery(str2);
        while(mycon2.rs.next())
        {
         str3="select DName from division where DID='"+mycon2.rs.getString("d.DID")+"'";
         System.out.println(str3);
         mycon1.rs=mycon1.stm.executeQuery(str3);
        if(mycon1.rs.next())
        {
            dname=mycon1.rs.getString("DName");
        
        }
        dtm1.addRow(new Object[]{mycon2.rs.getString("c.TrNo"),mycon2.rs.getString("a.PNR"),mycon2.rs.getString("b.Problem"),mycon2.rs.getString("a.Count"),dname});
        }
        jTable1.setModel(dtm1);
        }
        }catch(Exception e)
        {
        e.printStackTrace();
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TrainNo", "PNR", "Problem", "No of Compain ", "DivisionName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 850, 430);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\ICONS\\back-button1.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 470, 40, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\20 gradi\\photo-1508796079212-a4b83cbf734d.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
//        new Head().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
