/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.train;

import javax.swing.JOptionPane;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import java.io.*;
import javax.sound.sampled.Clip;
import parabitparis.train.tc.TrainTcMain;
import parabitparis.train.security.TrainSecurityMain;
import parabitparis.train.guardcoach.TrainGuardCoach;
import parabitparis.train.cleanning.TrainCleanningMain;
import parabitparis.train.pantry.TrainPantryMain;
import parabitparis.train.passenger.TrainPassengerMob;
import parabitparis.train.TrainEIDLogin;

/**
 *
 * @author HP
 */
public class TrainMain extends javax.swing.JFrame {

    /**
     * Creates new form TrainPessanger
     */
    String tn,bn;
    public TrainMain(String ss,String sr) {
        this.setUndecorated(true);
        initComponents();
        this.setBounds(250,170,820,450);
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\fire.jpg"));
        b25.setOpaque(false);
        b25.setContentAreaFilled(false);
        b25.setBorderPainted(false);
        b26.setOpaque(false);
        b26.setContentAreaFilled(false);
        b26.setBorderPainted(false);
        b27.setOpaque(false);
        b27.setContentAreaFilled(false);
        b27.setBorderPainted(false);
        b28.setOpaque(false);
        b28.setContentAreaFilled(false);
        b28.setBorderPainted(false);
        b29.setOpaque(false);
        b29.setContentAreaFilled(false);
        b29.setBorderPainted(false);
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
    tn=ss;
    bn=sr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b25 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b27 = new javax.swing.JButton();
        b28 = new javax.swing.JButton();
        b29 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        b25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b25.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\passanger.jpg")); // NOI18N
        b25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b25ActionPerformed(evt);
            }
        });
        getContentPane().add(b25);
        b25.setBounds(60, 78, 160, 90);

        b26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b26.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\TC.jpg")); // NOI18N
        b26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b26ActionPerformed(evt);
            }
        });
        getContentPane().add(b26);
        b26.setBounds(330, 20, 160, 90);

        b27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b27.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\pantry.jpg")); // NOI18N
        b27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b27ActionPerformed(evt);
            }
        });
        getContentPane().add(b27);
        b27.setBounds(600, 78, 160, 90);

        b28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b28.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\security.jpg")); // NOI18N
        b28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b28ActionPerformed(evt);
            }
        });
        getContentPane().add(b28);
        b28.setBounds(60, 280, 160, 90);

        b29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b29.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\cleaning.jpg")); // NOI18N
        b29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b29ActionPerformed(evt);
            }
        });
        getContentPane().add(b29);
        b29.setBounds(330, 330, 160, 100);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\gaurd.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 280, 160, 100);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 170, 160, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\railway.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 820, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b25ActionPerformed
       
       new TrainPassengerMob(this,true,tn,bn).setVisible(true);
       
        

// TODO add your handling code here:
    }//GEN-LAST:event_b25ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TrainEIDLogin(this,true,tn,bn,6).setVisible(true);
            
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b26ActionPerformed
        new TrainEIDLogin(this,true,tn,bn,2).setVisible(true);
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_b26ActionPerformed

    private void b29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b29ActionPerformed
        new TrainEIDLogin(this,true,tn,bn,5).setVisible(true);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_b29ActionPerformed

    private void b27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b27ActionPerformed
              new TrainEIDLogin(this,true,tn,bn,3).setVisible(true);
                
        
        // TODO add your handling code here:
    }//GEN-LAST:event_b27ActionPerformed

    private void b28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b28ActionPerformed
                    new TrainEIDLogin(this,true,tn,bn,4).setVisible(true);
                        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_b28ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        String filepath="alarm.wav";
        musicStuff(filepath);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b27;
    private javax.swing.JButton b28;
    private javax.swing.JButton b29;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

void musicStuff(String filelocation)
        
{  
       JOptionPane.showMessageDialog(null,"press OK if TRAIN is on FIRE");
    try{
    File filepath=new File(filelocation);
    AudioInputStream ais=AudioSystem.getAudioInputStream(filepath);
    Clip clip=AudioSystem.getClip();
    clip.open(ais);
    clip.start();
    clip.loop(Clip.LOOP_CONTINUOUSLY);
    JOptionPane.showMessageDialog(null,"press OK to Stops");
    clip.stop();
    }
    catch(Exception e){
        
//      e.printStackTrace();
    }
}
}
