/*public class TrainAdmin extends javax.swing.JFrame {

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.train;

import java.awt.Color;
import javax.swing.JOptionPane;
import parabitparis.PbtDbConn;

/**
 *
 * @author HP
 */
public class TrainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form TrainAdmin
     */
    int v,k;
    String al,tr,bn,sub2,sub,nextsid,sid,stop,sno;
    PbtDbConn mycon1,mycon3,mycon4,mycon2;
    public TrainAdmin(String ss,String sr) {
        initComponents();
        tf8.setOpaque(false);
        p3.setOpaque(false);
        tf8.setBackground(new Color(0,0,0,0));
        p3.setBackground(new Color(0,0,0,0));
        this.setBounds(450,260,480,280);
        b24.setOpaque(false);
        b24.setContentAreaFilled(false);
        b24.setBorderPainted(false);
        mycon1=new PbtDbConn();
        mycon2=new PbtDbConn();
        mycon3=new PbtDbConn();
        mycon4=new PbtDbConn();
        tr=ss;
        bn=sr;
        System.out.println(tr);
        sub2="select RID from troute where TrNo='"+tr+"'";
        try
        {  
           mycon3.rs=mycon3.stm.executeQuery(sub2);
           if(mycon3.rs.next())
           {
           v=mycon3.rs.getInt("RID");
           }
        }catch(Exception e)
        {
            System.out.println(e);
        }
 
sub="select a.SID,a.Stop,c.SName,b.RID,a.SNo from rstdetail a,troute b,station c where b.TrNo='"+tr+"' and a.RID=b.RID and c.SID=a.SID group by SNo";
       System.out.println(sub);
     
       try
       {   
           mycon1.rs=mycon1.stm.executeQuery(sub);                     
           if(mycon1.rs.next())
           {
               sid=mycon1.rs.getString("a.SID")+" "+mycon1.rs.getString("c.SName");
               stop=mycon1.rs.getString("a.Stop");
               sno=mycon1.rs.getString("a.SNo"); 
              
           }
       }catch(Exception e)
       {System.out.println(e); }
k=Integer.parseInt(sno)+1;
       String d="select a.SID,a.Stop,c.SName,b.RID,a.SNo from rstdetail a,troute b,station c where b.TrNo='"+tr+"' and a.RID=b.RID and c.SID=a.SID and SNo='"+k+"'";
       System.out.println(d);
       try
       {
        mycon4.rs=mycon4.stm.executeQuery(d);
        if(mycon4.rs.next())
        {
           nextsid=mycon4.rs.getString("a.SID")+" "+mycon4.rs.getString("SName");
        }
       }catch(Exception e)
       {System.out.println(e);}
 String p="insert into currentstatus values("+v+","+tr+","+sid.substring(0,4)+","+nextsid.substring(0,4)+","+sno+",'"+stop+"')";
         System.out.println(p);
            try
             {int l;
              l=mycon2.stm.executeUpdate(p);  
             }catch(Exception e)
             {System.out.println(e);}
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        b24 = new javax.swing.JButton();
        tf8 = new javax.swing.JTextField();
        p3 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Admin Id:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(72, 86, 92, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(72, 139, 92, 35);

        b24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b24.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\ICONS\\login.png")); // NOI18N
        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });
        getContentPane().add(b24);
        b24.setBounds(130, 210, 180, 50);
        getContentPane().add(tf8);
        tf8.setBounds(174, 88, 199, 33);

        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3ActionPerformed(evt);
            }
        });
        getContentPane().add(p3);
        p3.setBounds(174, 139, 199, 33);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\zon-login\\zon-login.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 500, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
      
         
        al="Select * from dutyreg a,emp b where a.TrNo='"+tr+"' and a.EID='"+tf8.getText()+"' and b.EID=a.EID  and b.Pswd='"+p3.getText()+"' and b.Des='TA'";
      System.out.println(al);
        try
        {
        mycon1.rs=mycon1.stm.executeQuery(al);
        if(mycon1.rs.next())
        {
          TrainMain ob2;
        ob2=new TrainMain(tr,bn);
        ob2.setVisible(true);   
        }
        
        }catch(Exception e)
        {
            System.out.println(e);
        }

       
        // TODO add your handling code here:
    }//GEN-LAST:event_b24ActionPerformed

    private void p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b24;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField p3;
    private javax.swing.JTextField tf8;
    // End of variables declaration//GEN-END:variables
}
