/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.train;
import java.awt.Color;
import javax.swing.JOptionPane;
import parabitparis.PbtDbConn;

/**
 *
 * @author HP
 */
public class TrainLogin extends javax.swing.JFrame {

    /**
     * Creates new form TrainLogin
     */
     String d;
    PbtDbConn mycon1;
    public TrainLogin() {
        this.setUndecorated(true);
        initComponents();
        this.setBounds(390,100,570,540);
        tf6.setOpaque(false);
        tf6.setBackground(new Color(0,0,0,0));
        tf7.setOpaque(false);
        tf7.setBackground(new Color(0,0,0,0));
        b23.setOpaque(false);
        b23.setContentAreaFilled(false);
        b23.setBorderPainted(false);
        mycon1=new PbtDbConn();
       // d="Select Coach from 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();
        tf7 = new javax.swing.JTextField();
        b23 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        l12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l12.setForeground(new java.awt.Color(240, 240, 240));
        l12.setText("Train Number");
        getContentPane().add(l12);
        l12.setBounds(60, 270, 130, 34);

        l13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l13.setForeground(new java.awt.Color(240, 240, 240));
        l13.setText("Bogi Number");
        getContentPane().add(l13);
        l13.setBounds(60, 340, 130, 42);

        tf6.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(tf6);
        tf6.setBounds(190, 270, 253, 44);

        tf7.setForeground(new java.awt.Color(240, 240, 240));
        tf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf7ActionPerformed(evt);
            }
        });
        getContentPane().add(tf7);
        tf7.setBounds(190, 350, 253, 40);

        b23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b23.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\SUBMIT.jpg")); // NOI18N
        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });
        getContentPane().add(b23);
        b23.setBounds(190, 430, 130, 42);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\train.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 90, 130, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\login-page.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed

        tf6.getText();
       tf7.getText();
       System.out.println(tf7.getText().contains("-"));
       
        String t1;
         t1="Select * from train where TrNo='"+tf6.getText()+"'";  
System.out.println(t1);        
        try
        {
            mycon1.rs=mycon1.stm.executeQuery(t1);
            if(mycon1.rs.next())
            {
                this.dispose();
               new TrainAdmin1(this,true,tf6.getText(),tf7.getText().toUpperCase()).setVisible(true);
           
            }else{JOptionPane.showMessageDialog(null,"Train No is incorrect");
            
            }
        }catch(Exception e)
        {
//            JOptionPane.showMessageDialog(null,"WRONG TRAIN\n OR BOGI ");
//            System.out.println(e);
        }
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_b23ActionPerformed

    private void tf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf7ActionPerformed
//tf7=tf7.getText().toUpperCase();        // TODO add your handling code here:
    }//GEN-LAST:event_tf7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b23;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    // End of variables declaration//GEN-END:variables
}
