/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.train;
import javax.swing.JOptionPane;
import parabitparis.PbtDbConn;
import parabitparis.train.cleanning.TrainCleanningMain1;
import parabitparis.train.guardcoach.TrainGuardCoach;
import parabitparis.train.pantry.TrainPantryMain;
import parabitparis.train.security.TrainSecurityMain;
import parabitparis.train.tc.TrainTcMain1;
import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author HP
 */
public class TrainEIDLogin extends javax.swing.JDialog {

    /**
     * Creates new form TrainEIDLogin
     */
    java.awt.Frame f;
    boolean b;
    PbtDbConn mycon1;
    String tn,bn;
    int des;
    public TrainEIDLogin(java.awt.Frame parent, boolean modal,String tn,String bn,int des) {
        super(parent, modal);
        initComponents();
        setIconImage();
        this.setBounds(450,260,480,300);
        jTextField1.setOpaque(false);
        jTextField1.setBackground(new Color(0,0,0,0));
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        f=parent;
        b=modal;
        this.tn=tn;
        this.bn=bn;
        this.des=des;
        mycon1=new PbtDbConn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("EID :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 90, 43, 41);

        jTextField1.setForeground(new java.awt.Color(240, 240, 240));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(224, 93, 168, 41);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\SUBMIT.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 160, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\login-page.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 550, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
         //    new TrainTcMain1(f,b,tn,bn).setVisible(true);
         //          this.dispose();
         
        
//        new TrainPantryMain(f,b,tn).setVisible(true);
//            this.dispose();
//            
//         new TrainSecurityMain(f,b,tn).setVisible(true);
//         this.dispose();
//                    
//           new TrainCleanningMain1(f,b,tn).setVisible(true);
//           this.dispose();
//           
//            new TrainGuardCoach(f,b,tn).setVisible(true);
//            this.dispose();
            
        switch(des){
            
            case 2:
        String str1="select * from emp  where EID='"+jTextField1.getText()+"' and Des='TC' and OnDuty='Y'";
        System.out.println(str1);
        try
        {
            mycon1.rs=mycon1.stm.executeQuery(str1);
            if(mycon1.rs.next()){
                this.dispose();
               new TrainTcMain1(f,b,tn,bn).setVisible(true);
               
            }else{
            JOptionPane.showMessageDialog(rootPane, "NOT VALID");}
        }catch(Exception e){
//            e.printStackTrace();
        }
            break;
            case 3:
                String str2="select * from emp where EID='"+jTextField1.getText()+"' and OnDuty='Y' and Des='PS'";
        try
        {
            mycon1.rs=mycon1.stm.executeQuery(str2);
            if(mycon1.rs.next()){
                this.dispose();
               new TrainPantryMain(f,b,tn).setVisible(true);
            
            }else{
            JOptionPane.showMessageDialog(rootPane, "NOT VALID");}
        }catch(Exception e){
//            e.printStackTrace();
        }
            break;
            case 4:
                String str3="select * from emp where EID='"+jTextField1.getText()+"' and OnDuty='Y' and Des='SS'";
        try
        {
            mycon1.rs=mycon1.stm.executeQuery(str3);
            if(mycon1.rs.next()){
                this.dispose();
                new TrainSecurityMain(f,b,tn).setVisible(true);
            
            }else{
            JOptionPane.showMessageDialog(rootPane, "NOT VALID");}
        }catch(Exception e){
//            e.printStackTrace();
        }
            break;
            case 5:
                String str4="select * from emp where EID='"+jTextField1.getText()+"' and OnDuty='Y' and Des='CS'";
        try
        {
            mycon1.rs=mycon1.stm.executeQuery(str4);
            if(mycon1.rs.next()){
                this.dispose();
                new TrainCleanningMain1(f,b,tn).setVisible(true);
            
            }else{
            JOptionPane.showMessageDialog(rootPane, "NOT VALID");}
        }catch(Exception e){
//            e.printStackTrace();
        }
            break;
            case 6:
                String str5="select * from emp where EID='"+jTextField1.getText()+"' and OnDuty='Y' and Des='GR'";
        try
        {
            mycon1.rs=mycon1.stm.executeQuery(str5);
            if(mycon1.rs.next()){
                
                this.dispose();
                new TrainGuardCoach(f,b,tn).setVisible(true);
            
            }else{
            JOptionPane.showMessageDialog(rootPane, "NOT VALID");}
        }catch(Exception e){
//            e.printStackTrace();
        }
            break;
                
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("FLAG22.png")));
    }

}
