/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.train.guardcoach;

/**
 *
 * @author HP
 */
import java.awt.Toolkit;
import java.lang.String;
import parabitparis.PbtDbConn;
public class TrainGuardCoach extends javax.swing.JDialog {

    /**
     * Creates new form TrainGuardCoach
     */
    
     String sid,sid2,st,sn,gm;
     String stop,sno;
     int k;
    String tn,sub,sub2,psid,nextsid;
    int v;
    PbtDbConn mycon1,mycon2,mycon3,mycon4;
    public TrainGuardCoach(java.awt.Frame parent, boolean modal,String ss) {
        super(parent, modal);
        initComponents();
        setIconImage();
       this.setBounds(265,170,805,478);
        b81.setOpaque(false);
        b81.setBorderPainted(false);
        b81.setContentAreaFilled(false);
        mycon1=new PbtDbConn();
        mycon2=new PbtDbConn();
        mycon3=new PbtDbConn();
        mycon4=new PbtDbConn();
        tn=ss;
        sub2="select RID from troute where TrNo='"+tn+"'";
        try
        {  
           mycon3.rs=mycon3.stm.executeQuery(sub2);
           if(mycon3.rs.next())
           {
           v=mycon3.rs.getInt("RID");
           }
        }catch(Exception e)
        {
//            System.out.println(e);
        }

        sub="select a.SID,a.Stop,c.SName,b.RID,a.SNo from rstdetail a,troute b,station c where b.TrNo='"+tn+"' and a.RID=b.RID and c.SID=a.SID group by SNo";
       System.out.println(sub);
     
       try
       {   
           mycon1.rs=mycon1.stm.executeQuery(sub);                     
           if(mycon1.rs.next())
           {
               sid=mycon1.rs.getString("a.SID")+" "+mycon1.rs.getString("c.SName");
               stop=mycon1.rs.getString("a.Stop");
               sno=mycon1.rs.getString("a.SNo"); 
              
           }
       }catch(Exception e)
       {
//           System.out.println(e);
       }
       l18.setText(sid);
       l19.setText(stop);
       l22.setText(sno);
       
       k=Integer.parseInt(sno)+1;
       String d="select a.SID,a.Stop,c.SName,b.RID,a.SNo from rstdetail a,troute b,station c where b.TrNo='"+tn+"' and a.RID=b.RID and c.SID=a.SID and SNo='"+k+"'";
       System.out.println(d);
       try
       {
        mycon4.rs=mycon4.stm.executeQuery(d);
        if(mycon4.rs.next())
        {
           nextsid=mycon4.rs.getString("a.SID")+" "+mycon4.rs.getString("SName");
        }
       }catch(Exception e)
       {
//           System.out.println(e);
       }
       l21.setText(nextsid);
       
       /* String p="insert into currentstatus values("+v+","+tn+","+sid.substring(0,4)+","+nextsid.substring(0,4)+","+sno+",'"+stop+"')";
         System.out.println(p);
            try
             {int l;
              l=mycon2.stm.executeUpdate(p);  
             }catch(Exception e)
             {System.out.println(e);}*/
              
       //System.out.println(sid2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        b81 = new javax.swing.JButton();
        l19 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        l17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l17.setForeground(new java.awt.Color(240, 240, 240));
        l17.setText("Previous Station:");
        getContentPane().add(l17);
        l17.setBounds(70, 70, 155, 39);

        l18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l18.setForeground(new java.awt.Color(240, 240, 240));
        l18.setText("START");
        getContentPane().add(l18);
        l18.setBounds(300, 70, 143, 39);

        b81.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b81.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\Pass.jpg")); // NOI18N
        b81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b81ActionPerformed(evt);
            }
        });
        getContentPane().add(b81);
        b81.setBounds(360, 280, 120, 70);

        l19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l19.setForeground(new java.awt.Color(240, 240, 240));
        l19.setText("Status");
        getContentPane().add(l19);
        l19.setBounds(494, 70, 100, 39);

        l20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l20.setForeground(new java.awt.Color(240, 240, 240));
        l20.setText("Next Station:");
        getContentPane().add(l20);
        l20.setBounds(80, 150, 155, 37);

        l21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l21.setForeground(new java.awt.Color(240, 240, 240));
        l21.setText("END");
        getContentPane().add(l21);
        l21.setBounds(300, 150, 143, 37);

        l22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l22.setForeground(new java.awt.Color(240, 240, 240));
        l22.setText("SNo");
        getContentPane().add(l22);
        l22.setBounds(650, 70, 63, 39);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\20 gradi\\xGsnNz.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b81ActionPerformed
        
        
        /* String y="select a.SID,a.Stop,c.SName,b.RID,a.SNo from rstdetail a,troute b,station c where b.TrNo='"+tn+"' and a.RID=b.RID and c.SID=a.SID group by SNo having SNo>=2";
         System.out.println(y);*/
         try
       {   
          // mycon1.rs=mycon1.stm.executeQuery(sub);
           if(mycon1.rs.next())
       {
           sid=mycon1.rs.getString("a.SID")+" "+mycon1.rs.getString("c.SName");
           stop=mycon1.rs.getString("a.Stop");
           sno=mycon1.rs.getString("a.SNo"); 
       }
       }catch(Exception e)
       {
//           System.out.println(e);
       }
         l18.setText(sid);
         l19.setText(stop);
         l22.setText(sno);
         k=Integer.parseInt(sno)+1;
         String q="select a.SID,c.SName from rstdetail a,troute b,station c where b.TrNo='"+tn+"' and a.RID=b.RID and c.SID=a.SID and SNo='"+k+"'";
         System.out.println(q);
         try
         {
          mycon3.rs=mycon3.stm.executeQuery(q);
          if(mycon3.rs.next())
          {
              nextsid=mycon3.rs.getString("a.SID")+" "+mycon3.rs.getString("c.SName");
          }
         }catch(Exception e){
//             System.out.println(e);
         }
         
         l21.setText(nextsid);
         psid=l18.getText();
         System.out.println(l18.getText().substring(0,4));
        
         gm="update currentstatus set RID="+v+",TrNo="+tn+",PrevSID="+psid.substring(0,4)+",NextSID="+nextsid.substring(0,4)+",SNo="+sno+",Stop='"+stop+"' where TrNo='"+tn+"'";
         System.out.println(gm);
         try
         {int m;
           m=mycon2.stm.executeUpdate(gm);
           System.out.println(m);
         }catch(Exception e)
         {
//             System.out.println(e);
         }
         if(l18.getText().equals(l21.getText()))
            {
                l21.setText("END");
                b81.setEnabled(false);
            }
            
            
        // TODO add your handling code here:
    }//GEN-LAST:event_b81ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b81;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    // End of variables declaration//GEN-END:variables
private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("FLAG22.png")));
    }

}
