/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.train.tc;


import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import parabitparis.PbtDbConn;


/**
 *
 * @author HP
 */
public class TrainTcMain extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form TrainTC
     */
    int sno;
    PbtDbConn mycon3;
    boolean b=true;
    Thread th;
    String mys,pn,sn,co;
    DefaultTableColumnModel m1,m2,m3;
    PbtDbConn mycon1,mycon2;
     Object[] m,h,s;
     DefaultTableModel dtm,dtm1,dtm2;
    String tn,bn,nn,prob;
    java.awt.Frame f;
    boolean g;
    public TrainTcMain(java.awt.Frame parent, boolean modal,String sc,String se) {
        initComponents();
        this.setBounds(100,370,800,400);
        tn=sc;
        bn=se;
        f=parent;
        g=modal;
        mycon1=new PbtDbConn();
        mycon2=new PbtDbConn();
        mycon3=new PbtDbConn();
        th=new Thread(this);
         dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setColumnCount(4);
        Object[] v=new Object[]{"PNR","Seat No","Coach","Problem"};
        dtm.setColumnIdentifiers(v);
        dtm.fireTableDataChanged();
        dtm1=(DefaultTableModel)jTable2.getModel();
        dtm1.setColumnCount(4);
        Object[] q=new Object[]{"PNR","Seat No","Coach","Problem"};
        dtm1.setColumnIdentifiers(q);
        dtm1.fireTableDataChanged();
        dtm2=(DefaultTableModel)jTable3.getModel();
        dtm2.setColumnCount(4);
        Object[] n=new Object[]{"PNR","Seat No","Coach","Problem"};
        dtm2.setColumnIdentifiers(n);
        dtm2.fireTableDataChanged();

        nn="Select a.PNR,a.Seat,a.Coach,a.PrId,b.Problem from rtproblem a,problemrt b where (a.PrID='PR 3' and b.PrID='PR 3')or(a.PrID='PR 4' and b.PrID='PR 4')or(a.PrID='PR 9' and b.PrID='PR 9')or(a.PrID='PR 10' and b.PrID='PR 10')or(a.PrID='PR 19' and b.PrID='PR 19')or(a.PrID='PR 20' and b.PrID='PR 20')or(a.PrID='PR 21' and b.PrID='PR 21')or(a.PrID='PR 22' and b.PrID='PR 22')or(a.PrID='PR 23' and b.PrID='PR 23')or(a.PrID='PR 24' and b.PrID='PR 24')";
        System.out.println(nn);
        try{
        mycon1.rs=mycon1.stm.executeQuery(nn);
        dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
         dtm1.setRowCount(0);
          dtm2.setRowCount(0);
       while(mycon1.rs.next())
       {
            mycon1.rs.getString("a.PrID");
            pn=mycon1.rs.getString("a.PNR");
            sn=mycon1.rs.getString("a.Seat");
            co=mycon1.rs.getString("a.Coach");
            prob=mycon1.rs.getString("b.Problem");
            System.out.println(prob+"-----");
       /* if(mycon1.rs.getString("PrID").equals("PR 9")||mycon1.rs.getString("PrID").equals("PR 10"));
        {
            m=new Object[]{prob};
            System.out.println(m);
            dtm.addRow(m);
            jTable1.setModel(dtm);
        }*/
        if(mycon1.rs.getString("PrID").equals("PR 9")||mycon1.rs.getString("PrID").equals("PR 10")){
            m=new Object[]{pn,sn,co,prob};
            System.out.println(m);
            dtm.addRow(m);
            jTable1.setModel(dtm);
        }
        else{
                
                
       if(mycon1.rs.getString("PrID").equals("PR 19")||mycon1.rs.getString("PrID").equals("PR 21")||mycon1.rs.getString("PrID").equals("PR 22")||mycon1.rs.getString("PrID").equals("PR 23")||mycon1.rs.getString("PrID").equals("PR 24")||mycon1.rs.getString("PrID").equals("PR 20"))
       {
       s=new Object[]{pn,sn,co,prob};
           dtm1.addRow(s);
           jTable2.setModel(dtm1);
       }
                else{
                
       if(mycon1.rs.getString("PrId").equals("PR 3")||mycon1.rs.getString("PrID").equals("PR 4"))
       {
           h=new Object[]{prob};
           dtm2.addRow(new Object[]{pn,sn,co,prob});
           jTable3.setModel(dtm2);
           
       }
                }
        }
                
        }  }catch(Exception e){System.out.println(e);}
      th.start();  
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void run(){
        while(b){
        nn="Select a.PNR,a.Seat,a.Coach,a.PrId,b.Problem from rtproblem a,problemrt b where (a.PrID='PR 3' and b.PrID='PR 3')or(a.PrID='PR 4' and b.PrID='PR 4')or(a.PrID='PR 9' and b.PrID='PR 9')or(a.PrID='PR 10' and b.PrID='PR 10')or(a.PrID='PR 19' and b.PrID='PR 19')or(a.PrID='PR 20' and b.PrID='PR 20')or(a.PrID='PR 21' and b.PrID='PR 21')or(a.PrID='PR 22' and b.PrID='PR 22')or(a.PrID='PR 23' and b.PrID='PR 23')or(a.PrID='PR 24' and b.PrID='PR 24')";
        System.out.println(nn);
        try{
            th.sleep(15000);
        mycon1.rs=mycon1.stm.executeQuery(nn);
        dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
         dtm1.setRowCount(0);
          dtm2.setRowCount(0);
       while(mycon1.rs.next())
       {
            mycon1.rs.getString("a.PrID");
            pn=mycon1.rs.getString("a.PNR");
            sn=mycon1.rs.getString("a.Seat");
            co=mycon1.rs.getString("a.Coach");
            prob=mycon1.rs.getString("b.Problem");
            System.out.println(prob+"-----");
       /* if(mycon1.rs.getString("PrID").equals("PR 9")||mycon1.rs.getString("PrID").equals("PR 10"));
        {
            m=new Object[]{prob};
            System.out.println(m);
            dtm.addRow(m);
            jTable1.setModel(dtm);
        }*/
        if(mycon1.rs.getString("PrID").equals("PR 9")||mycon1.rs.getString("PrID").equals("PR 10")){
            m=new Object[]{pn,sn,co,prob};
            System.out.println(m);
            dtm.addRow(m);
            jTable1.setModel(dtm);
        }
        else{
                
                
       if(mycon1.rs.getString("PrID").equals("PR 19")||mycon1.rs.getString("PrID").equals("PR 21")||mycon1.rs.getString("PrID").equals("PR 22")||mycon1.rs.getString("PrID").equals("PR 23")||mycon1.rs.getString("PrID").equals("PR 24")||mycon1.rs.getString("PrID").equals("PR 20"))
       {
       s=new Object[]{pn,sn,co,prob};
           dtm1.addRow(s);
           jTable2.setModel(dtm1);
       }
                else{
                
       if(mycon1.rs.getString("PrId").equals("PR 3")||mycon1.rs.getString("PrID").equals("PR 4"))
       {
           h=new Object[]{prob};
           dtm2.addRow(new Object[]{pn,sn,co,prob});
           jTable3.setModel(dtm2);
           
       }
                }
        }
         
        }  }catch(Exception e){System.out.println(e);
        }
        if(this.isShowing()==false){
            System.out.println(this.isShowing()+" "+"ggg");
            th.stop();
           
        }
        }}
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(48, 135, 281, 199);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("TC Main");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(18, 11, 126, 47);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Other Problem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 380, 127, 54);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Complain About Pessanger");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 380, 205, 54);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("TC Problem");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(830, 380, 129, 54);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(378, 110, 290, 224);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(721, 132, 264, 202);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mechanical");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(48, 100, 116, 24);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Security");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(486, 73, 96, 26);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Health");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(934, 95, 79, 26);

        jButton4.setText("Drop Request");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(48, 381, 124, 54);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\multi.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1060, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
            TrainTcProb ttcp;
            ttcp=new TrainTcProb(this,g,tn,bn);
            ttcp.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String sid="";    
        String prevsid="";
        String eid="";
            String ud="";
            int rid=0;
            String g="",g1="";
            String h1="select a.UD,b.PrevSID,b.SNo,b.RID from troute a,currentstatus b where a.TrNo='"+tn+"'and b.TrNo='"+tn+"'";
            System.out.println(h1);
            try{
            mycon1.rs=mycon1.stm.executeQuery(h1);
            if(mycon1.rs.next()){
            ud=mycon1.rs.getString("UD");
            System.out.println(ud);
            prevsid=mycon1.rs.getString("PrevSID");
            sno=mycon1.rs.getInt("SNo");
            rid=mycon1.rs.getInt("RID");
            
            }
             if(ud.equals("u")){
             g="select SID,Stop from rstdetail where SNo>='"+sno+"'";
             
             try{mycon2.rs=mycon2.stm.executeQuery(g);
             while(mycon2.rs.next()){
             if(mycon2.rs.getString("Stop").equals("Y")){
             sid=mycon2.rs.getString("SID");
             break;
             }
             }
             String str3="select EID from dutyreg where Res like('%"+bn+"%') or Res like('"+bn+"%') or Res like('%"+bn+"') and TrNo='"+tn+"'";
             System.out.println(str3);
             mycon1.rs=mycon1.stm.executeQuery(str3);
             mycon1.rs.next();
             eid=mycon1.rs.getString("EID");
             String str4="update emp set OnDuty='DR-"+sid+"' where EID='"+eid+"'";
             System.out.println(str4);
             mycon3.stm.executeUpdate(str4);
             }catch(Exception e){e.printStackTrace();}
             }else{
             g1="select SID,Stop from rstdetail wehere SNo<='"+sno+"'";
             try{mycon2.rs=mycon2.stm.executeQuery(g1);
             while(mycon2.rs.next()){
             if(mycon2.rs.getString("Stop").equals("Y")){
             sid=mycon2.rs.getString("SID");
             break;
             }
             }
             String str3="select EID from dutyreg where Res like('%"+bn+"%') or Res like('"+bn+"%') or Res like('%"+bn+"') and TrNo='"+tn+"'";
             System.out.println(str3);
             mycon1.rs=mycon1.stm.executeQuery(str3);
             mycon1.rs.next();
             eid=mycon1.rs.getString("EID");
             String str4="update emp set OnDuty='DR-"+sid+"' where EID='"+eid+"'";
             System.out.println(str4);
             mycon3.stm.executeUpdate(str4);
             }catch(Exception e){e.printStackTrace();}
             }   
            }
           catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
