/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.train.tc;

import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import parabitparis.PbtDbConn;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class TrainTcProb extends javax.swing.JDialog implements Runnable {

    /**
     * Creates new form TrainTCProblem
     * 
     */
    
    DefaultTableModel dtm;
    Thread th;
    boolean j=true;
    String tn,bn,mm;
    PbtDbConn mycon1,mycon2,mycon3;
    java.awt.Frame f;
     boolean b;
     int q=0;
    public TrainTcProb(java.awt.Frame parent, boolean modal,String se,String sc) {
        super(parent, modal);
        initComponents();
        setIconImage();
        this.setBounds(220,180,770,420);
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        f=parent;
        th=new Thread(this);
        
        b=modal;
        tn=se;
        bn=sc;
        mycon1=new PbtDbConn();
        mycon2=new PbtDbConn();
        mycon3=new PbtDbConn();
        DefaultTableModel dtm1=(DefaultTableModel)jTable1.getModel();
        dtm1.setColumnCount(4);
        Object[] b=new Object[]{"PNR","Seat No","Coach","Problem"};
        dtm1.setColumnIdentifiers(b);
        
        
        mm="Select a.PNR,a.Seat,a.Coach,b.Problem from rtproblem a,problemrt b where a.PrID='PR 24' and b.PrID=a.PrID and a.Status='N'";
        System.out.println(mm);
        try{
            mycon1.rs=mycon1.stm.executeQuery(mm);
         dtm=(DefaultTableModel)jTable1.getModel();
         dtm.setRowCount(0);
         while(mycon1.rs.next()){
          Object[] r=new Object[]{mycon1.rs.getString("a.PNR"),mycon1.rs.getString("a.Seat"),mycon1.rs.getString("a.Coach"),mycon1.rs.getString("b.Problem")};   
          dtm.addRow(r);
         }
         jTable1.setModel(dtm);
        }catch(Exception e){
            e.printStackTrace();
        }
        th.start(); 
       // dtm1.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 30, 660, 300);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\back-button.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 350, 50, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\solved1.jpg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 350, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\j14165U.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        th.stop();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                
            dtm.getValueAt(jTable1.getSelectedRow(),0);
        String rt="update rtproblem a,problemrt b set a.status='S' where a.PNR='"+dtm.getValueAt(jTable1.getSelectedRow(),0)+"' and a.PrID=b.PrID and b.Problem='"+dtm.getValueAt(jTable1.getSelectedRow(),3)+"' and a.coach='"+dtm.getValueAt(jTable1.getSelectedRow(),2)+"'";
        System.out.println(rt);
        try{
           mycon2.stm.executeUpdate(rt);
        }   catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please Select from above");
//            e.printStackTrace();
        }         
                dtm.removeRow(jTable1.getSelectedRow());
                 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void run(){
        System.out.println("Start");
      try{
          while(j){
         mycon1.rs=mycon1.stm.executeQuery(mm);
         dtm=(DefaultTableModel)jTable1.getModel();
         dtm.setRowCount(0);
         while(mycon1.rs.next()){
          Object[] r=new Object[]{mycon1.rs.getString("a.PNR"),mycon1.rs.getString("a.Seat"),mycon1.rs.getString("a.Coach"),mycon1.rs.getString("b.Problem")};   
          dtm.addRow(r);
         }
         jTable1.setModel(dtm);
         th.sleep(15000);
      }
        }catch(Exception e){
            System.out.println(e);
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("FLAG22.png")));
    }

}
