/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.station;

import java.awt.Color;
import javax.swing.JOptionPane;
import parabitparis.PbtDbConn;
import java.awt.Toolkit;

/**
 *
 * @author HP
 */


public class EmployeLogin extends javax.swing.JDialog {
     PbtDbConn mycon;
    
    /**
     * Creates new form EmployeLogin
     * @param ob
     */
     
    
       
     
    String s;
    String s1,s2;
    java.awt.Frame f;
    boolean ob2;   
  String sid,des;
  int cas=0;
    public EmployeLogin(java.awt.Frame parent, boolean modal,String sid,int cas,String des) {
        super(parent, modal);
      this.setUndecorated(false);
        initComponents();
        setIconImage();
        tf4.setOpaque(false);
        tf5.setOpaque(false);
        tf4.setBackground(new Color(0,0,0,0));
        tf5.setBackground(new Color(0,0,0,0));
        this.setBounds(450,260,480,300);
        mycon=new PbtDbConn();
         this.sid=sid;
         this.des=des;
         this.cas=cas;
      f=parent;
      ob2=modal;
      }
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        b10 = new javax.swing.JButton();
        tf4 = new javax.swing.JTextField();
        tf5 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("EID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(96, 80, 90, 27);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(85, 130, 100, 34);

        b10.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\login.png")); // NOI18N
        b10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b10MouseEntered(evt);
            }
        });
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10);
        b10.setBounds(140, 200, 180, 50);

        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });
        getContentPane().add(tf4);
        tf4.setBounds(190, 70, 184, 39);
        getContentPane().add(tf5);
        tf5.setBounds(190, 130, 184, 44);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\zon-login\\zon-login.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 510, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf4ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
      // new StationMaster(f,ob2,sid).setVisible(true);
      // this.dispose();
   // new StaffAllotD1(f,ob2,sid).setVisible(true);
   // this.dispose();
    // new CleaningManager(f,ob2,sid).setVisible(true);
     //this.dispose();
     ///new PantryManager(f,ob2,sid).setVisible(true);
    // this.dispose();
   //   new SecurityManager(f,ob2,sid).setVisible(true);
  //   this.dispose();
        
   /// new TrainMaintain(f,ob2,sid).setVisible(true);
    // this.dispose();
        
      //   new HelthManager(f,ob2,sid).setVisible(true);
    // this.dispose();
    //  new HelpDesk(f,ob2,sid).setVisible(true);
  //  this.dispose();
//  new TCManager(f,ob2,sid).setVisible(true);
  //   this.dispose();

   
     sid="7520";
        switch(cas){
           case 1:
               s1=tf4.getText();
                s2=tf5.getText();
s="Select * from emp where EID='"+s1+"' AND Pswd='"+s2+"' AND SID='"+sid+"' and Des='"+des+"'";
System.out.println(s);
try
{
mycon.rs=mycon.stm.executeQuery(s);
if(mycon.rs.next()==true)
{
    //System.out.println("valid");
    this.setVisible(false);
   new StationMaster(f,ob2,sid).setVisible(true);
 
}
else{
    JOptionPane.showMessageDialog(rootPane,"NOT VALID");
}
}catch(Exception e)
        {
//            System.out.println(e);
        }          
               break;
           case 2:      
s1=tf4.getText();
s2=tf5.getText();
s="Select * from emp where EID='"+s1+"' AND Pswd='"+s2+"' AND SID='"+sid+"' and Des='"+des+"'";
System.out.println(s);
try
{
mycon.rs=mycon.stm.executeQuery(s);
if(mycon.rs.next()==true)
{
    //System.out.println("valid");
 this.setVisible(false);
    new StaffAllotD1(f,ob2,sid).setVisible(true);
     
}
else{
    JOptionPane.showMessageDialog(rootPane,"NOT VALID");
}
}catch(Exception e)
        {
//            System.out.println(e);
        }
           break;
           case 3:
                s1=tf4.getText();
                s2=tf5.getText();
s="Select * from emp where EID='"+s1+"' AND Pswd='"+s2+"' AND SID='"+sid+"' and Des='"+des+"'";
System.out.println(s);
try
{
mycon.rs=mycon.stm.executeQuery(s);
if(mycon.rs.next()==true)
{
    //System.out.println("valid");
    this.setVisible(false);
    new CleaningManager(f,ob2,sid).setVisible(true);
     
}
else{
    JOptionPane.showMessageDialog(rootPane,"NOT VALID");
}
}catch(Exception e)
        {
//            System.out.println(e);
        }      
               break;
           case 4:
                s1=tf4.getText();
                s2=tf5.getText();
s="Select * from emp where EID='"+s1+"' AND Pswd='"+s2+"' AND SID='"+sid+"' and Des='"+des+"'";
System.out.println(s);
try
{
mycon.rs=mycon.stm.executeQuery(s);
if(mycon.rs.next()==true)
{
  this.setVisible(false);   
//System.out.println("valid"); 
 new PantryManager(f,ob2,sid).setVisible(true);
    
}
else{
    JOptionPane.showMessageDialog(rootPane,"NOT VALID");
}
}catch(Exception e)
        {
//            System.out.println(e);
        }
               break;
           case 5:
                s1=tf4.getText();
                s2=tf5.getText();
s="Select * from emp where EID='"+s1+"' AND Pswd='"+s2+"' AND SID='"+sid+"' and Des='"+des+"'";
System.out.println(s);
try
{
mycon.rs=mycon.stm.executeQuery(s);
if(mycon.rs.next()==true)
{
    this.setVisible(false);
    //System.out.println("valid");
    new SecurityManager(f,ob2,sid).setVisible(true);
     
}
else{
    JOptionPane.showMessageDialog(rootPane,"NOT VALID");

}
}catch(Exception e)
        {
//            System.out.println(e);
        }
               break;
           case 6:
                s1=tf4.getText();
                s2=tf5.getText();
s="Select * from emp where EID='"+s1+"' AND Pswd='"+s2+"' AND SID='"+sid+"' and Des='"+des+"'";
System.out.println(s);
try
{
mycon.rs=mycon.stm.executeQuery(s);
if(mycon.rs.next()==true)
{
    //System.out.println("valid");
   this.setVisible(false);
  new TrainMaintain(f,ob2,sid).setVisible(true);
     
}
else{
    JOptionPane.showMessageDialog(rootPane,"NOT VALID");
}
}catch(Exception e)
        {
//            System.out.println(e);
        }
               break;
           case 7:
                s1=tf4.getText();
                s2=tf5.getText();
s="Select * from emp where EID='"+s1+"' AND Pswd='"+s2+"' AND SID='"+sid+"' and Des='"+des+"'";
System.out.println(s);
try
{
mycon.rs=mycon.stm.executeQuery(s);
if(mycon.rs.next()==true)
{
    this.setVisible(false);
    //System.out.println("valid");
  new HelthManager(f,ob2,sid).setVisible(true);
     
}
else{
    JOptionPane.showMessageDialog(rootPane,"NOT VALID");

}
}catch(Exception e)
        {
//            System.out.println(e);
        }
               
               break;
           case 8:
                s1=tf4.getText();
                s2=tf5.getText();
s="Select * from emp where EID='"+s1+"' AND Pswd='"+s2+"' AND SID='"+sid+"' and Des='"+des+"'";
System.out.println(s);
try
{
mycon.rs=mycon.stm.executeQuery(s);
if(mycon.rs.next()==true)
{
    //System.out.println("valid");
   this.setVisible(false);
    new HelpDesk(f,ob2,sid).setVisible(true);
     
}
else{
    JOptionPane.showMessageDialog(rootPane,"NOT VALID");
}
}catch(Exception e)
        {
//            System.out.println(e);
        }
               break;
           case 9:
                s1=tf4.getText();
                s2=tf5.getText();
s="Select * from emp where EID='"+s1+"' AND Pswd='"+s2+"' AND SID='"+sid+"' and Des='"+des+"'";
System.out.println(s);
try
{
mycon.rs=mycon.stm.executeQuery(s);
if(mycon.rs.next()==true)
{
    this.setVisible(false);
    //System.out.println("valid");
    new TCManager(f,ob2,sid).setVisible(true);
     
}
else{
    JOptionPane.showMessageDialog(rootPane,"NOT VALID");
}
}catch(Exception e)
        {
//            System.out.println(e);
        }
               break;          
       }
    }//GEN-LAST:event_b10ActionPerformed

    private void b10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_b10MouseEntered

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tf4;
    private javax.swing.JPasswordField tf5;
    // End of variables declaration//GEN-END:variables
public void setIconImage(){
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("FLAG22.PNG")));
}

}
