    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.station;

import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import parabitparis.PbtDbConn;

/**
 *
 * @author HP
 */
public class HelthManager extends javax.swing.JDialog implements Runnable {

    /**
     * Creates new form HelthManager
     */
     String y1="";
    
    boolean b=true;
    Thread th;
    PbtDbConn mycon1,mycon2;
    DefaultTableModel dtm1;
    java.awt.Frame f;
    boolean bo;
    String sid;
    public HelthManager(java.awt.Frame parent, boolean modal,String sid) {
        super(parent, modal);
        initComponents();
        setIconImage();
         this.setBounds(250,120,835,548);
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        this.sid=sid;
        th=new Thread((Runnable)this);
        mycon1=new PbtDbConn();
        mycon2=new PbtDbConn();
        dtm1=(DefaultTableModel)jTable1.getModel();
        //dtm1.setColumnCount(5);
        dtm1.setRowCount(0);
        y1="select a.TrNo,b.PNR,b.Seat,b.Coach,c.Problem from ps a,rtproblem b,problemrt c where a.PNR=b.PNR and c.PrID=b.PrID and ((b.PrID='PR 3') or (b.PrID='PR 4')) and b.Status='PS-"+sid+"' group by b.PrID";
       System.out.println(y1);
        try{
           mycon1.rs=mycon1.stm.executeQuery(y1);
       while(mycon1.rs.next()){
           dtm1.addRow(new Object[]{mycon1.rs.getString("TrNo"),mycon1.rs.getString("PNR"), mycon1.rs.getString("Seat"),mycon1.rs.getString("Coach"),mycon1.rs.getString("Problem")});
       }
       jTable1.setModel(dtm1);
       }catch(SQLException e){
       e.printStackTrace();
       }
        th.start();
    }
    public void run(){
     
        while(b){
            
    try{
        th.sleep(15000);
        System.out.println(y1);
         dtm1.setRowCount(0);
           mycon1.rs=mycon1.stm.executeQuery(y1);
        while(mycon1.rs.next()){
           dtm1.addRow(new Object[]{mycon1.rs.getString("TrNo"),mycon1.rs.getString("PNR"), mycon1.rs.getString("Seat"),mycon1.rs.getString("Coach"),mycon1.rs.getString("Problem")});
       }
       jTable1.setModel(dtm1);
       }catch(SQLException e){
       e.printStackTrace();
       }catch(Exception e){
       e.printStackTrace();
       }
    }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TrainNo", "PNR", "SeatNo", "Coach", "Problem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 40, 770, 371);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Helth Manager:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(34, 11, 170, 23);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\Pass.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(590, 430, 130, 50);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\solved1.jpg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(110, 430, 130, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\dynamic-animation-smooth-gradient-background-footage-090800298_prevstill.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 830, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             dtm1.getValueAt(jTable1.getSelectedRow(),1);
        String rt="update rtproblem a,problemrt b set a.status='S' where a.PNR='"+dtm1.getValueAt(jTable1.getSelectedRow(),1)+"'and a.PrID=b.PrID and b.Problem='"+dtm1.getValueAt(jTable1.getSelectedRow(),4)+"' and a.coach='"+dtm1.getValueAt(jTable1.getSelectedRow(),3)+"'";
        System.out.println(rt);
        try{
           mycon2.stm.executeUpdate(rt);
        }   catch(SQLException e){
            JOptionPane.showMessageDialog(null,"PLEASE SELECT ");
//            e.printStackTrace();
        }         
                dtm1.removeRow(jTable1.getSelectedRow());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String str="update rtproblem a,problemrt b set a.Status='PS1-"+sid+"' where a.PNR='"+dtm1.getValueAt(jTable1.getSelectedRow(),1)+"'and a.PrID=b.PrID and b.Problem='"+dtm1.getValueAt(jTable1.getSelectedRow(),4)+"' and a.coach='"+dtm1.getValueAt(jTable1.getSelectedRow(),3)+"'";
     System.out.println(str);
     try{
     mycon2.stm.executeUpdate(str);
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"PLEASE SELECT ");
//     e.printStackTrace();
     }
     dtm1.removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("FLAG22.png")));
    }
}
