/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.station;

import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import parabitparis.PbtDbConn;

/**
 *
 * @author HP
 */
public class PantryManager extends javax.swing.JDialog implements Runnable {

    /**
     * Creates new form PantryManager
     */
    Thread th;
    boolean b=true;
    boolean f;
    java.awt.Frame p;
    String y1="";
    DefaultTableModel dtm1;
    PbtDbConn mycon1,mycon2;
    String sid;
    public PantryManager(java.awt.Frame parent, boolean modal,String sid) {
        super(parent, modal);
        initComponents();
        setIconImage();
        p=parent;f=modal;
        this.setBounds(250,140,890,497);
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton3.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton3.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        jButton3.setBorderPainted(false);
        this.sid=sid;
        th=new Thread(this);
        mycon1=new PbtDbConn();
       dtm1=(DefaultTableModel)jTable1.getModel();
       dtm1.setRowCount(0);
       y1="Select a.TrNo,b.PNR,b.Seat,b.Coach,c.Problem from ps a,rtproblem b,problemrt c where a.PNR=b.PNR and c.PrID=b.PrID and b.Status='PS-"+sid+"' and ((b.PrID='PR 15') or (b.PrID='PR 16') or (b.PrID='PR 17') or (b.PrID='PR 18') or (b.PrID='PR 14')) group by b.PrID";
       System.out.println(y1);
       try{
           mycon1.rs=mycon1.stm.executeQuery(y1);
           while(mycon1.rs.next()){
           dtm1.addRow(new Object[]{mycon1.rs.getString("TrNo"),mycon1.rs.getString("PNR"),mycon1.rs.getString("Seat"),mycon1.rs.getString("Coach"),mycon1.rs.getString("Problem")});
           }
           jTable1.setModel(dtm1);
       }catch(SQLException e){
       e.printStackTrace();
       }
    th.start();
    }
    public void run(){
    while(b){
    try{
        th.sleep(15000);
        dtm1.setRowCount(0);
           mycon1.rs=mycon1.stm.executeQuery(y1);
           while(mycon1.rs.next()){
           dtm1.addRow(new Object[]{mycon1.rs.getString("TrNo"),mycon1.rs.getString("PNR"),mycon1.rs.getString("Seat"),mycon1.rs.getString("Coach"),mycon1.rs.getString("Problem")});
           }
           jTable1.setModel(dtm1);
       }catch(SQLException e){
       e.printStackTrace();
       }catch(Exception e){
       e.printStackTrace();
       }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TrainNo", "PNR", "SeatNo", "Coach", "Problem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(38, 44, 802, 324);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Pantry Manager:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 230, 30);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\solved1.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 400, 120, 47);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\Pass.jpg")); // NOI18N
        jButton2.setMaximumSize(new java.awt.Dimension(165, 87));
        jButton2.setMinimumSize(new java.awt.Dimension(165, 87));
        jButton2.setPreferredSize(new java.awt.Dimension(165, 87));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 400, 120, 47);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\view.jpg")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(670, 400, 120, 47);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\multi.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 890, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                     dtm1.getValueAt(jTable1.getSelectedRow(),1);
        String rt="update rtproblem a,problemrt b set a.status='S' where a.PNR='"+dtm1.getValueAt(jTable1.getSelectedRow(),1)+"'and a.PrID=b.PrID and b.Problem='"+dtm1.getValueAt(jTable1.getSelectedRow(),4)+"' and a.coach='"+dtm1.getValueAt(jTable1.getSelectedRow(),3)+"'";
        System.out.println(rt);
        try{
           mycon2.stm.executeUpdate(rt);
        }   catch(SQLException e){
            JOptionPane.showMessageDialog(null,"PLEASE SELECT ");
//            e.printStackTrace();
        }         
                dtm1.removeRow(jTable1.getSelectedRow());

        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String str="update rtproblem a,problemrt b set a.Status='PS1-"+sid+"' where a.PNR='"+dtm1.getValueAt(jTable1.getSelectedRow(),1)+"'and a.PrID=b.PrID and b.Problem='"+dtm1.getValueAt(jTable1.getSelectedRow(),4)+"' and a.coach='"+dtm1.getValueAt(jTable1.getSelectedRow(),3)+"'";
     System.out.println(str);
     try{
     mycon2.stm.executeUpdate(str);
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"PLEASE SELECT ");
//     e.printStackTrace();
     }
     dtm1.removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new PantryManagerAll(p,f).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("FLAG22.png")));
    }
}
