/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.station;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import parabitparis.PbtDbConn;
/**
 *
 * @author HP
 */
public class StaffDropReq extends javax.swing.JDialog implements Runnable {

    /**
     * Creates new form StaffDropReq1
     */
    boolean b=true;
    Thread th;
    PbtDbConn mycon1,mycon2;
    java.awt.Frame p;
    boolean m;
    String sid,str1,str2,s;
    DefaultTableModel dtm1;
    public StaffDropReq(java.awt.Frame parent, boolean modal,String sid) {
        super(parent, modal);
        initComponents();
        this.setBounds(290,130,760,497);
         jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        jTable1.setOpaque(false);
        jTable1.setBackground(new Color(0,0,0,0));
        p=parent;
        m=modal;
        th=new Thread(this);
        mycon1=new PbtDbConn();
        mycon2=new PbtDbConn();
        this.sid=sid;
        dtm1=(DefaultTableModel)jTable1.getModel();
        dtm1.setRowCount(0);
        str2="select Stop from rstdetail where SID='"+this.sid+"'";
        try{
        mycon2.rs=mycon2.stm.executeQuery(str2);
        mycon2.rs.next();
        s=mycon2.rs.getString("Stop");
        str1="select a.TrNo,b.EID,b.ENm,b.Des from troute a,emp b,rstdetail c where c.SID='"+this.sid+"' and a.RID=c.RID and c.Stop='"+s+"' and b.OnDuty='DR-"+sid+"'and a.UD='u'";
        System.out.println(str1);
        
        mycon1.rs=mycon1.stm.executeQuery(str1);
        while(mycon1.rs.next()){
        dtm1.addRow(new Object[]{mycon1.rs.getString("TrNo"),mycon1.rs.getString("EID"),mycon1.rs.getString("ENm"),mycon1.rs.getString("Des")});
        }
        jTable1.setModel(dtm1);
        }catch(Exception e){
//        e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void run(){
        while(b){
            dtm1.setRowCount(0);
        try{
        th.sleep(15000);
        mycon2.rs=mycon2.stm.executeQuery(str2);
        mycon2.rs.next();
        s=mycon2.rs.getString("Stop");
        mycon1.rs=mycon1.stm.executeQuery(str1);
        while(mycon1.rs.next()){
        dtm1.addRow(new Object[]{mycon1.rs.getString("TrNo"),mycon1.rs.getString("EID"),mycon1.rs.getString("ENm"),mycon1.rs.getString("Des")});
        }
        jTable1.setModel(dtm1);
                }catch(Exception e){
//                    e.printStackTrace();
                }
    }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\DROP REQUEST\\REJECT1.jpg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 390, 140, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Drop Request:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 390, 113, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Train No", "EmpID", "EmpName", "Desig"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(24, 23, 700, 348);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\DROP REQUEST\\ACCEPT1.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 390, 140, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\20 gradi\\xGsnNz.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 760, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String str2="update emp set OnDuty='Y' where OnDuty='DR-"+sid+"'";
        try{
        mycon1.stm.executeUpdate(str2);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"PLEASE SELECT");
//            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTable1.getSelectedRowCount()==0){
        JOptionPane.showMessageDialog(null,"PLEASE SELECT");
        }
        else
        {
        new StaffAllotRun1(p,m,sid).setVisible(true);
        }
//        catch( Exception e)
//                {
//                
//                }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
