/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.station;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Collection;
import parabitparis.PbtDbConn;

/**
 *
 * @author HP
 */
public class StaffAllotD2 extends javax.swing.JDialog {
    
    /**
     * Creates new form StaffAllotD2
     */
    PbtDbConn mycon,mycon1;
    java.awt.Frame f;
    boolean ob2;
   String s1,s2,s3,s4,s5,s6,c,s7,req;
    public StaffAllotD2(java.awt.Frame parent, boolean modal,String sid) {
        super(parent, modal);
        initComponents();
        setIconImage();
        this.setBounds(213,180,915,410);
        f=parent;
        s1=sid;
        ob2=modal;
        mycon1=new PbtDbConn();
        
         mycon =new PbtDbConn(); 
             s2="Select b.TrNo from rstdetail a,troute b where a.SNo='1' and a.SID='"+s1+"' AND b.RID=a.RID and b.UD='u'";
        System.out.println(s2);
        try
        {
        mycon.rs=mycon.stm.executeQuery(s2);
       
     while(mycon.rs.next())
        {
            System.out.println(mycon.rs);
            s3=mycon.rs.getString("b.TrNo");
            jcb1.addItem(s3);
           
            
        }
        }
       catch(Exception e)
       {
          System.out.println(e);
       }
        s4=(String)jcb1.getSelectedItem();
    }
         
         
             
         
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l6 = new javax.swing.JLabel();
        jcb1 = new javax.swing.JComboBox();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        l6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l6.setForeground(new java.awt.Color(240, 240, 240));
        l6.setText("STAFF ALLOTMENT FOR NEW TRAIN :");
        getContentPane().add(l6);
        l6.setBounds(120, 50, 320, 30);

        jcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb1ActionPerformed(evt);
            }
        });
        getContentPane().add(jcb1);
        jcb1.setBounds(440, 50, 185, 30);

        b13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b13.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\staffD2\\DRIVER1.jpg")); // NOI18N
        b13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b13MouseEntered(evt);
            }
        });
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        getContentPane().add(b13);
        b13.setBounds(50, 130, 150, 70);

        b14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b14.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\staffD2\\GUARD1.jpg")); // NOI18N
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        getContentPane().add(b14);
        b14.setBounds(270, 130, 150, 70);

        b15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b15.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\staffD2\\TC SLEEPER1.jpg")); // NOI18N
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });
        getContentPane().add(b15);
        b15.setBounds(500, 130, 150, 70);

        b16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b16.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\staffD2\\TCAC1.jpg")); // NOI18N
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        getContentPane().add(b16);
        b16.setBounds(722, 130, 140, 70);

        b17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b17.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\staffD2\\SECURITY.jpg")); // NOI18N
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });
        getContentPane().add(b17);
        b17.setBounds(50, 255, 150, 70);

        b18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b18.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\staffD2\\PANTRY1.jpg")); // NOI18N
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });
        getContentPane().add(b18);
        b18.setBounds(500, 255, 150, 70);

        b19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b19.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\staffD2\\CLEANING1.jpg")); // NOI18N
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });
        getContentPane().add(b19);
        b19.setBounds(720, 255, 140, 70);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\staffD2\\AQDMIN1.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 255, 150, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\shimla.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed

        jcb1.setSelectedItem("14623");
    req="Select DR from train where TrNo='"+jcb1.getSelectedItem()+"'";
    System.out.println(req);
         try
         {
             mycon1.rs=mycon1.stm.executeQuery(req);
             if(mycon1.rs.next())
             {
             mycon1.rs.getString("DR");

        StaffAllotD3 ob;
ob=new StaffAllotD3(f,ob2,s1,s4,"Driver","DR",mycon1.rs.getString("DR"));
ob.setVisible(true);
  }
         }catch(Exception e)
                 {
//                     System.out.println(e);
                 }
            
           

// TODO add your handling code here:
    }//GEN-LAST:event_b13ActionPerformed

    private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1ActionPerformed
    if(evt.getSource()==jcb1)
    {
        s4=(String)jcb1.getSelectedItem();
    }
// TODO add your handling code here:
    }//GEN-LAST:event_jcb1ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
      
          req="Select GR from train where TrNo='"+jcb1.getSelectedItem()+"'";
           System.out.println(req);
         try
         {
             mycon1.rs=mycon1.stm.executeQuery(req);
             if(mycon1.rs.next())
             {
             mycon1.rs.getString("GR");
      
          StaffAllotD3 ob;
          ob=new StaffAllotD3(f,ob2,s1,s4,"Guard","GR",mycon1.rs.getString("GR"));
          ob.setVisible(true);
  }
         }
           catch(Exception e)
                 {
//                     System.out.println(e);
                 }
          
      
        

// TODO add your handling code here:
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
    
      
          req="Select TCSL from train where TrNo='"+jcb1.getSelectedItem()+"'";
           System.out.println(req);
         try
         {
             mycon1.rs=mycon1.stm.executeQuery(req);
             if(mycon1.rs.next())
             {
             mycon1.rs.getString("TCSL");
               StaffAllotD3 ob;
          ob=new StaffAllotD3(f,ob2,s1,s4,"TCSleeper","TC",mycon1.rs.getString("TCSL"));
          ob.setVisible(true);
             }
            
          }catch(Exception e)
                 {
//                     System.out.println(e);
                 }
    
      
        // TODO add your handling code here:
    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
         
        
          req="Select TCAC from train where TrNo='"+jcb1.getSelectedItem()+"'";
           System.out.println(req);
         try
         {
             mycon1.rs=mycon1.stm.executeQuery(req);
             if(mycon1.rs.next())
             {
             mycon1.rs.getString("TCAC");
          StaffAllotD3 ob;
          ob=new StaffAllotD3(f,ob2,s1,s4,"TCAC","TC",mycon1.rs.getString("TCAC"));
          ob.setVisible(true);
             }
           }catch(Exception e)
                 {
//                     System.out.println(e);
                 }
          
      
        // TODO add your handling code here:
    }//GEN-LAST:event_b16ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
          if(evt.getSource()==b17)
      {  
 req="Select SS from train where TrNo='"+jcb1.getSelectedItem()+"'";
  System.out.println(req);
         try
         {
             mycon1.rs=mycon1.stm.executeQuery(req);
             if(mycon1.rs.next())
             {
             mycon1.rs.getString("SS");
          StaffAllotD3 ob;
          ob=new StaffAllotD3(f,ob2,s1,s4,"Security","SS",mycon1.rs.getString("SS"));
          ob.setVisible(true);
             }
            
         } catch(Exception e)
                 {
//                     System.out.println(e);
                 }
          
      } 
        // TODO add your handling code here:
    }//GEN-LAST:event_b17ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
         if(evt.getSource()==b18)
      {  
          req="Select PS from train where TrNo='"+jcb1.getSelectedItem()+"'";
           System.out.println(req);
         try
         {
             mycon1.rs=mycon1.stm.executeQuery(req);
             if(mycon1.rs.next())
             {
             mycon1.rs.getString("PS");
      }
          StaffAllotD3 ob;
          ob=new StaffAllotD3(f,ob2,s1,s4,"Pantry","PS",mycon1.rs.getString("PS"));
          ob.setVisible(true);
             }
            
           catch(Exception e)
                 {
//                     System.out.println(e);
                 }
          
      }
        

// TODO add your handling code here:
    }//GEN-LAST:event_b18ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
         if(evt.getSource()==b19)
         {
             req="Select CS from train where TrNo='"+jcb1.getSelectedItem()+"'";
              System.out.println(req);
         try
         {
             mycon1.rs=mycon1.stm.executeQuery(req);
             if(mycon1.rs.next())
             {
             mycon1.rs.getString("CS");
         }
            StaffAllotD3 ob;
            ob=new StaffAllotD3(f,ob2,s1,s4,"Cleanliness","CS", mycon1.rs.getString("CS"));
            ob.setVisible(true);
               }
            
           catch(Exception e)
                 {
//                     System.out.println(e);
                 }
         }        
// TODO add your handling code here:
    }//GEN-LAST:event_b19ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
//        String ta;
        req="Select TA from train where TrNo='"+jcb1.getSelectedItem()+"'";
        try{
       mycon1.rs=mycon1.stm.executeQuery(req);
       if(mycon1.rs.next()){
            mycon1.rs.getString("TA");
        }
       StaffAllotD3 ob;
          ob=new StaffAllotD3(f,ob2,s1,s4,"Admin","TA",mycon1.rs.getString("TA"));
          ob.setVisible(true);
        }
        catch(Exception e)
        {
        
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_b13MouseEntered

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox jcb1;
    private javax.swing.JLabel l6;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("FLAG22.png")));
    }
}
