/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.station;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import parabitparis.PbtDbConn;

/**
 *
 * @author HP
 */
public class StaffAllotRun1 extends javax.swing.JDialog implements Runnable {

    /**
     * Creates new form StaffAllotRun11
     */
    Thread th;
    PbtDbConn mycon1,mycon2,mycon3;
    String str1,str2,str3,str4;
    DefaultListModel dlm,dlm1;
    String sid;
    boolean b=true;
    public StaffAllotRun1(java.awt.Frame parent, boolean modal,String sid) {
        super(parent, modal);
        initComponents();
        
        setIconImage();
         this.setBounds(360,180,640,397);
         jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        this.sid=sid;
        th=new Thread(this);
        mycon1=new PbtDbConn();
        mycon2=new PbtDbConn();
        mycon3=new PbtDbConn();
       dlm =new DefaultListModel();
       dlm1 =new DefaultListModel();
       str1="select EID from emp where OnDuty='DR-"+sid+"'";
       str2="select EID from emp where SID='"+sid+"' and OnDuty='N' and Des='TC'";
       System.out.println(str1);
       System.out.println(str2);
       try{
           mycon2.rs=mycon2.stm.executeQuery(str1);
       mycon1.rs=mycon1.stm.executeQuery(str2);
       while(mycon1.rs.next()){
           
       dlm1.addElement(mycon1.rs.getString("EID").toString());
       }
       jList2.setModel(dlm1);
       while(mycon2.rs.next()){
       dlm.addElement(mycon2.rs.getString("EID").toString());
       }
       jList1.setModel(dlm);
       }catch(SQLException e){
//           e.printStackTrace();
       }
    th.start();
    }

    public void run(){
        while(b){
    try{
     th.sleep(15000);
     dlm1.removeAllElements();
     dlm.removeAllElements();
    mycon2.rs=mycon2.stm.executeQuery(str1);
       mycon1.rs=mycon1.stm.executeQuery(str2);
       while(mycon1.rs.next()){
           
       dlm1.addElement(mycon1.rs.getString("EID").toString());
       }
       jList2.setModel(dlm1);
       while(mycon2.rs.next()){
       dlm.addElement(mycon2.rs.getString("EID").toString());
       }
       jList1.setModel(dlm);
    }catch(Exception e){
//        e.printStackTrace();
    }
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\swapw.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 190, 140, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("On Duty");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(151, 60, 66, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Off Duty");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 60, 68, 22);

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(51, 110, 166, 195);

        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(420, 110, 161, 195);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\new.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 630, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String str1="update emp set OnDuty='N' where EID='"+jList1.getSelectedValue()+"'";
       String str2="update emp set Onduty='Y' where EID='"+jList2.getSelectedValue()+"'";
       String str3="update dutyreg set SwapWithEID='"+jList2.getSelectedValue()+"' where EID='"+jList1.getSelectedValue()+"'";
       System.out.println(str1);
       System.out.println(str2);
       System.out.println(str3);
       try{
           mycon3.stm.executeUpdate(str1);
           mycon3.stm.executeUpdate(str2);
           mycon3.stm.executeUpdate(str3);
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,"PLEASE SELECT");
//           e.printStackTrace();
       }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("FLAG22.png")));
    }

}
