
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.station;

/**
 *
 * @author HP
 */
import java.awt.Color;
//import java.sql.*;
import javax.swing.JOptionPane;
import parabitparis.PbtDbConn;

public class StationLogin extends javax.swing.JFrame {

    /**
     * Creates new form StationLogin
     */
PbtDbConn mycon;
    public StationLogin() {
        this.setUndecorated(true);
        initComponents();
        tf1.setOpaque(false);
        tf2.setOpaque(false);
        tf3.setOpaque(false);
        tf1.setBackground(new Color(0,0,0,0));
        tf2.setBackground(new Color(0,0,0,0));
        tf3.setBackground(new Color(0,0,0,0));
        this.setBounds(370,100,600,600);
        try
        {
              mycon = new PbtDbConn();

        }
        catch(Exception e)
                {
//                    System.out.println(e);
                   
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        tf2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        l1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\ICONS\\lock.png")); // NOI18N
        getContentPane().add(l1);
        l1.setBounds(220, 240, 40, 40);

        l2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\ICONS\\xx.png")); // NOI18N
        getContentPane().add(l2);
        l2.setBounds(220, 310, 40, 40);

        tf1.setText("Username");
        tf1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf1MouseClicked(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(290, 240, 220, 40);

        l3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(0, 0, 0));
        l3.setText("Station ID");
        getContentPane().add(l3);
        l3.setBounds(183, 385, 97, 31);

        tf3.setText("Station ID");
        tf3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf3MouseClicked(evt);
            }
        });
        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        getContentPane().add(tf3);
        tf3.setBounds(292, 385, 220, 40);

        b1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\ICONS\\login.png")); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(230, 470, 190, 50);

        tf2.setText("pass");
        tf2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf2MouseClicked(evt);
            }
        });
        getContentPane().add(tf2);
        tf2.setBounds(290, 310, 220, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\ICONS\\user.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 50, 140, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\login-page.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
       
        String s1,s2,sid;
s1=tf1.getText();
s2=tf2.getText();

sid=tf3.getText();

  //  sid="7520";

String s ="select * from emp where EID='"+s1+"' and pswd='"+s2+"' AND SID='"+sid+"' ";
System.out.println(s);
try
{               
    
    
              
    
             mycon.rs =mycon.stm.executeQuery(s);
             if(mycon.rs.next()==true)
             {
                 this.setVisible(false);
              new Station(sid).setVisible(true);
              
             //System.out.println("Valid user");
             }
             else
             {
             JOptionPane.showMessageDialog(null,"INVALID USER");
             
             }
}catch(Exception e)
{

}
//EmployeLogin ob=new EmployeLogin(s3);
// TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void tf1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf1MouseClicked
tf1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_tf1MouseClicked

    private void tf2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf2MouseClicked
tf2.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_tf2MouseClicked

    private void tf3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf3MouseClicked
tf3.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_tf3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StationLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StationLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StationLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StationLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StationLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JTextField tf1;
    private javax.swing.JPasswordField tf2;
    private javax.swing.JTextField tf3;
    // End of variables declaration//GEN-END:variables
}
