/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.station;

/**
 *
 * @author HP
 */
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import parabitparis.PbtDbConn;
import javax.swing.table.DefaultTableModel;
public class TrainMaintain extends javax.swing.JDialog implements Runnable {

    /**
     * Creates new form TrainMaintain
     */
    
    boolean b=true;
    boolean f;
    java.awt.Frame p;
    PbtDbConn mycon1,mycon2;
    Thread th;
    String str;
    DefaultTableModel dtm1;
    String sid;
    public TrainMaintain(java.awt.Frame parent, boolean modal,String sid) {
        super(parent, modal);
        initComponents();
        setIconImage();
         f=modal;
         p=parent;
       this.setBounds(210,130,900,560);
       jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        jTable1.setOpaque(false);
        jTable1.setBackground(new Color(0,0,0,0));
        mycon2=new PbtDbConn();
        this.sid=sid;
        mycon1=new PbtDbConn();
        th=new Thread((Runnable)this);
        dtm1=(DefaultTableModel)jTable1.getModel();
        str="select a.TrNo,b.PNR,b.Seat,b.Coach,c.Problem from ps a,rtproblem b,problemrt c where a.PNR=b.PNR and c.PrID=b.PrID and ((b.PrID='PR 7') or (b.PrID='PR 8') or (b.PrID='PR 9') or (b.PrID='PR 10')) and b.Status='PS-"+sid+"' group by b.PrID";
        try{
            mycon1.rs=mycon1.stm.executeQuery(str);
            while(mycon1.rs.next()){
            dtm1.addRow(new Object[]{mycon1.rs.getString("TrNo"),mycon1.rs.getString("PNR"),mycon1.rs.getString("Seat"),mycon1.rs.getString("Coach"),mycon1.rs.getString("Problem")});
            }
            jTable1.setModel(dtm1);
        }catch(Exception e){
//        e.printStackTrace();
        }
        th.start();
    }
public void run(){
while(b){
 try{
            mycon1.rs=mycon1.stm.executeQuery(str);
            while(mycon1.rs.next()){
            dtm1.addRow(new Object[]{mycon1.rs.getString("TrNo"),mycon1.rs.getString("PNR"),mycon1.rs.getString("Seat"),mycon1.rs.getString("Coach"),mycon1.rs.getString("Problem")});
            }
            jTable1.setModel(dtm1);
        }catch(Exception e){
//        e.printStackTrace();
        }
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TrainNo", "PNR", "SeatNo", "Coach", "problem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(25, 28, 836, 402);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\Pass.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 450, 110, 50);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\view.jpg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 450, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\20 gradi\\xGsnNz.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dtm1.getValueAt( jTable1.getSelectedRow(), 1);
       String h="update rtproblem a,problemrt b set a.Status='PS1-"+sid+"' where a.PNR='"+dtm1.getValueAt(jTable1.getSelectedRow(),1)+"'and a.PrID=b.PrID and b.Problem='"+dtm1.getValueAt(jTable1.getSelectedRow(),4)+"' and a.coach='"+dtm1.getValueAt(jTable1.getSelectedRow(),3)+"'";
       try{
           mycon2.stm.executeUpdate(h);
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,"PLEASE SELECT");
//       e.printStackTrace();
       }
       dtm1.removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new TrainMaintainAll(p,f).setVisible(true); 
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("FLAG22.png")));
    }
}
