/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.train.passenger;

import parabitparis.PbtDbConn;
import parabitparis.train.passenger.TrainSecurity;
import parabitparis.train.passenger.TrainClean;
import parabitparis.train.passenger.TrainWater;
import parabitparis.train.passenger.TrainPantry;
import parabitparis.train.passenger.TrainDiffCoach;
import parabitparis.train.passenger.TrainOther;
import parabitparis.train.passenger.TrainMisBehave;
import parabitparis.train.passenger.TrainHealth;
import parabitparis.train.passenger.TrainElectrical;
import parabitparis.train.passenger.TrainCorruption;
import parabitparis.train.passenger.TrainMechanical;
import java.awt.Toolkit;
/**
 *
 * @author HP
 */
public class TrainProblem extends javax.swing.JDialog {

    /**
     * Creates new form PassengerProblem
     */
    PbtDbConn mycon1,mycon2;
    java.awt.Frame f;
    boolean b;
    String bn,mob,tn,k,g,se;
    public TrainProblem(java.awt.Frame parent, boolean modal,String sr,String no,String mm) {
        super(parent, modal);
        initComponents();
        this.setBounds(210,110,950,580);
        b31.setOpaque(false);
        b31.setContentAreaFilled(false);
        b31.setBorderPainted(false);
        b32.setOpaque(false);
        b32.setContentAreaFilled(false);
        b32.setBorderPainted(false);
        b33.setOpaque(false);
        b33.setContentAreaFilled(false);
        b33.setBorderPainted(false);
        b34.setOpaque(false);
        b34.setContentAreaFilled(false);
        b34.setBorderPainted(false);
        b35.setOpaque(false);
        b35.setContentAreaFilled(false);
        b35.setBorderPainted(false);
        b37.setOpaque(false);
        b37.setContentAreaFilled(false);
        b37.setBorderPainted(false);
        b38.setOpaque(false);
        b38.setContentAreaFilled(false);
        b38.setBorderPainted(false);
        b39.setOpaque(false);
        b39.setContentAreaFilled(false);
        b39.setBorderPainted(false);
        b41.setOpaque(false);
        b41.setContentAreaFilled(false);
        b41.setBorderPainted(false);
        b40.setOpaque(false);
        b40.setContentAreaFilled(false);
        b40.setBorderPainted(false);
        
        f=parent;
        b=modal;
        bn=sr;
        mob=no;
        tn=mm;
        mycon2=new PbtDbConn();
        mycon1=new PbtDbConn();
        k="select Coach,SeatNo from ps where PMob1='"+mob+"' or PMob2='"+mob+"'";
        System.out.println(k);
        try{
            mycon2.rs=mycon2.stm.executeQuery(k);
            if(mycon2.rs.next())
            {
             g=mycon2.rs.getString("Coach");
             se=mycon2.rs.getString("SeatNo");
            }
                }catch(Exception e){
//                    System.out.println(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b31 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        b34 = new javax.swing.JButton();
        b35 = new javax.swing.JButton();
        b37 = new javax.swing.JButton();
        b38 = new javax.swing.JButton();
        b39 = new javax.swing.JButton();
        b40 = new javax.swing.JButton();
        b41 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        b31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b31.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\trainhealth.jpg")); // NOI18N
        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31ActionPerformed(evt);
            }
        });
        getContentPane().add(b31);
        b31.setBounds(690, 290, 122, 80);

        b32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b32.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\trainwater.jpg")); // NOI18N
        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32ActionPerformed(evt);
            }
        });
        getContentPane().add(b32);
        b32.setBounds(127, 50, 140, 80);

        b33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b33.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\trainmechanical.jpg")); // NOI18N
        b33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b33ActionPerformed(evt);
            }
        });
        getContentPane().add(b33);
        b33.setBounds(130, 170, 140, 80);

        b34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b34.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\trainpantry.jpg")); // NOI18N
        b34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b34ActionPerformed(evt);
            }
        });
        getContentPane().add(b34);
        b34.setBounds(690, 50, 122, 80);

        b35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b35.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\traincleaning.jpg")); // NOI18N
        b35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b35ActionPerformed(evt);
            }
        });
        getContentPane().add(b35);
        b35.setBounds(410, 50, 142, 80);

        b37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b37.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\trainsecurity.jpg")); // NOI18N
        b37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b37ActionPerformed(evt);
            }
        });
        getContentPane().add(b37);
        b37.setBounds(690, 160, 122, 80);

        b38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b38.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\trainothers.jpg")); // NOI18N
        b38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b38ActionPerformed(evt);
            }
        });
        getContentPane().add(b38);
        b38.setBounds(410, 290, 142, 80);

        b39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b39.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\trainelectricity.jpg")); // NOI18N
        b39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b39ActionPerformed(evt);
            }
        });
        getContentPane().add(b39);
        b39.setBounds(130, 290, 140, 80);

        b40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b40.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\traincorruption.jpg")); // NOI18N
        b40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b40ActionPerformed(evt);
            }
        });
        getContentPane().add(b40);
        b40.setBounds(410, 160, 142, 80);

        b41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b41.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\button2\\trainmiss.jpg")); // NOI18N
        b41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b41ActionPerformed(evt);
            }
        });
        getContentPane().add(b41);
        b41.setBounds(390, 420, 180, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\kalka-shimla.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-30, 0, 970, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32ActionPerformed
     
      //  TrainWater ob1;
//        ob1=new TrainWater(f,b,bn,mob,tn,se);
//        ob1.setVisible(true);
//        this.dispose();
        
        if(bn.equals(g)){
        TrainWater ob1;
        ob1=new TrainWater(f,b,bn,mob,tn,se);
        ob1.setVisible(true);
        }else
        {
            TrainDiffCoach tb;
            tb=new TrainDiffCoach(f,b,"TrainWater",bn,g,mob,tn,se);
            tb.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_b32ActionPerformed

    private void b35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b35ActionPerformed
      
       
        
        
        if(bn.equals(g)){   
        TrainClean tc;
            tc=new TrainClean(f,b,bn,mob,tn,se);
            tc.setVisible(true);
        }else{
            TrainDiffCoach tb;
            tb=new TrainDiffCoach(f,b,"TrainClean",bn,g,mob,tn,se);
            tb.setVisible(true);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_b35ActionPerformed

    private void b33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b33ActionPerformed
     if(bn.equals(g)){
        TrainMechanical mec;
     mec=new TrainMechanical(f,b,bn,mob,tn,se);
     mec.setVisible(true);
     }else{
         TrainDiffCoach tb;
         tb=new TrainDiffCoach(f,b,"TrainMechanical",bn,g,mob,tn,se);
         tb.setVisible(true);
     }
     
        // TODO add your handling code here:
    }//GEN-LAST:event_b33ActionPerformed

    private void b34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b34ActionPerformed
       if(bn.equals(g)){
        TrainPantry tp;
        tp=new TrainPantry(f,b,bn,mob,tn,se);
        tp.setVisible(true);
       }else{
           TrainDiffCoach tb;
           tb=new TrainDiffCoach(f,b,"TrainPantry",bn,g,mob,tn,se);
           tb.setVisible(true);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_b34ActionPerformed

    private void b41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b41ActionPerformed
       
//         TrainMisBehave tmb;
//        tmb=new TrainMisBehave(f,b,bn,mob,tn,se);
//        tmb.setVisible(true);
//        this.dispose();
        
        if(bn.equals(g)){
        TrainMisBehave tmb;
        tmb=new TrainMisBehave(f,b,bn,mob,tn,se);
        tmb.setVisible(true);
        }else{
            TrainDiffCoach tb;
            tb=new TrainDiffCoach(f,b,"TrainMissBehave",bn,g,mob,tn,se);
            tb.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_b41ActionPerformed

    private void b40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b40ActionPerformed
      if(bn.equals(g)){
//        TrainCorruption tc;
       new TrainCorruption(f,b,bn,mob,tn,se).setVisible(true);
      }else{
//          TrainDiffCoach tb;
          new TrainDiffCoach(f,b,"TrinCorruption",bn,g,mob,tn,se).setVisible(true);
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_b40ActionPerformed

    private void b37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b37ActionPerformed
        
//        TrainSecurity ts;
//          ts=new TrainSecurity(f,b,bn,mob,tn,se);
//          ts.setVisible(true);
//        this.dispose();
        
        
        if(bn.equals(g)){ 
//        TrainSecurity ts;
          new TrainSecurity(f,b,bn,mob,tn,se).setVisible(true);
        }else{
//            TrainDiffCoach tb;
            new TrainDiffCoach(f,b,"TrainSecurity",bn,g,mob,tn,se).setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_b37ActionPerformed

    private void b39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b39ActionPerformed
      
//         TrainElectrical te;
//        te=new TrainElectrical(f,b,bn,mob,tn,se);
//        te.setVisible(true);
//        this.dispose();
        
        
        if(bn.equals(g)){
        TrainElectrical te;
        te=new TrainElectrical(f,b,bn,mob,tn,se);
        te.setVisible(true);
       }else
       {
           TrainDiffCoach tb;
           tb=new TrainDiffCoach(f,b,"TrainElectrical",bn,g,mob,tn,se);
           tb.setVisible(true);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_b39ActionPerformed

    private void b38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b38ActionPerformed
     
//         TrainOther to;
//to=new TrainOther(f,b,bn,mob,tn,se);
//to.setVisible(true);
//this.dispose();
        
        
        if(bn.equals(g)){
//        TrainOther to;
        new TrainOther(f,b,bn,mob,tn,se).setVisible(true);
        }else{
//            TrainDiffCoach tb;
            new TrainDiffCoach(f,b,"TrainOther",bn,g,mob,tn,se).setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_b38ActionPerformed

    private void b31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31ActionPerformed
       
//         TrainHealth th;
//        th=new TrainHealth(f,b,bn,mob,tn,se);
//        th.setVisible(true);
//        this.dispose();
        
        
        if(bn.equals(g)){
//        TrainHealth th;
        new TrainHealth(f,b,bn,mob,tn,se).setVisible(true);
        }else{
            new TrainDiffCoach(f,b,"TrainHealth",bn,g,mob,tn,se);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_b31ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b34;
    private javax.swing.JButton b35;
    private javax.swing.JButton b37;
    private javax.swing.JButton b38;
    private javax.swing.JButton b39;
    private javax.swing.JButton b40;
    private javax.swing.JButton b41;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
