/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.train.passenger;
import java.awt.Toolkit;
import parabitparis.PbtDbConn;
import java.awt.Color;

/**
 *
 * @author HP
 */
public class TrainPassengerMob extends javax.swing.JDialog {

    /**
     * Creates new form PassengerLogin
     */
    PbtDbConn mycon1;
    java.awt.Frame f;
    boolean b;
    String tn,bn;
    public TrainPassengerMob(java.awt.Frame parent, boolean modal,String ss,String sr) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();
        setIconImage();
        
        this.setBounds(450,200,400,430);
        l16.setOpaque(false);
        l16.setBackground(new Color(0,0,0,0));
        tf10.setOpaque(false);
        tf10.setBackground(new Color(0,0,0,0));
        b30.setOpaque(false);
        b30.setContentAreaFilled(false);
        b30.setBorderPainted(false);
        b44.setOpaque(false);
        b44.setContentAreaFilled(false);
        b44.setBorderPainted(false);
        b45.setOpaque(false);
        b45.setContentAreaFilled(false);
        b45.setBorderPainted(false);
        b46.setOpaque(false);
        b46.setContentAreaFilled(false);
        b46.setBorderPainted(false);
        b47.setOpaque(false);
        b47.setContentAreaFilled(false);
        b47.setBorderPainted(false);
        b48.setOpaque(false);
        b48.setContentAreaFilled(false);
        b48.setBorderPainted(false);
        b49.setOpaque(false);
        b49.setContentAreaFilled(false);
        b49.setBorderPainted(false);
        b50.setOpaque(false);
        b50.setContentAreaFilled(false);
        b50.setBorderPainted(false);
        b51.setOpaque(false);
        b51.setContentAreaFilled(false);
        b51.setBorderPainted(false);
        b52.setOpaque(false);
        b52.setContentAreaFilled(false);
        b52.setBorderPainted(false);
        b53.setOpaque(false);
        b53.setContentAreaFilled(false);
        b53.setBorderPainted(false);
        b54.setOpaque(false);
        b54.setContentAreaFilled(false);
        b54.setBorderPainted(false);
        b55.setOpaque(false);
        b55.setContentAreaFilled(false);
        b55.setBorderPainted(false);
        f=parent;
        b=modal;
        mycon1=new PbtDbConn();
        tn=ss;
        bn=sr;
        b44.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\MOb\\1.jpg"));
        b45.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\MOb\\2.jpg"));
        b46.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\MOb\\3.jpg"));
        b47.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\MOb\\4.jpg"));
        b48.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\MOb\\5.jpg"));
        b50.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\MOb\\7.jpg"));
        b51.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\MOb\\8.jpg"));
        b54.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\MOb\\0.jpg"));
        b52.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\MOb\\9.jpg"));
        b49.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\MOb\\6.jpg"));
        b53.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\MOb\\Cle.jpg"));
        b55.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\MOb\\Del.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l16 = new javax.swing.JLabel();
        tf10 = new javax.swing.JTextField();
        b30 = new javax.swing.JButton();
        b44 = new javax.swing.JButton();
        b45 = new javax.swing.JButton();
        b46 = new javax.swing.JButton();
        b47 = new javax.swing.JButton();
        b48 = new javax.swing.JButton();
        b49 = new javax.swing.JButton();
        b51 = new javax.swing.JButton();
        b52 = new javax.swing.JButton();
        b50 = new javax.swing.JButton();
        b54 = new javax.swing.JButton();
        b53 = new javax.swing.JButton();
        b55 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        l16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l16.setForeground(new java.awt.Color(240, 240, 240));
        l16.setText("Mobile no:");
        getContentPane().add(l16);
        l16.setBounds(54, 83, 91, 25);

        tf10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf10.setForeground(new java.awt.Color(240, 240, 240));
        tf10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf10ActionPerformed(evt);
            }
        });
        getContentPane().add(tf10);
        tf10.setBounds(155, 77, 151, 39);

        b30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b30.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\OK1.jpg")); // NOI18N
        b30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b30ActionPerformed(evt);
            }
        });
        getContentPane().add(b30);
        b30.setBounds(140, 360, 110, 40);

        b44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b44ActionPerformed(evt);
            }
        });
        getContentPane().add(b44);
        b44.setBounds(110, 130, 40, 30);

        b45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b45ActionPerformed(evt);
            }
        });
        getContentPane().add(b45);
        b45.setBounds(180, 130, 40, 30);

        b46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b46ActionPerformed(evt);
            }
        });
        getContentPane().add(b46);
        b46.setBounds(250, 130, 40, 30);

        b47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b47ActionPerformed(evt);
            }
        });
        getContentPane().add(b47);
        b47.setBounds(110, 190, 40, 30);

        b48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b48ActionPerformed(evt);
            }
        });
        getContentPane().add(b48);
        b48.setBounds(180, 190, 40, 30);

        b49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b49ActionPerformed(evt);
            }
        });
        getContentPane().add(b49);
        b49.setBounds(250, 190, 40, 30);

        b51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b51ActionPerformed(evt);
            }
        });
        getContentPane().add(b51);
        b51.setBounds(180, 250, 40, 30);

        b52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b52ActionPerformed(evt);
            }
        });
        getContentPane().add(b52);
        b52.setBounds(250, 250, 40, 30);

        b50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b50ActionPerformed(evt);
            }
        });
        getContentPane().add(b50);
        b50.setBounds(110, 250, 40, 30);

        b54.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b54ActionPerformed(evt);
            }
        });
        getContentPane().add(b54);
        b54.setBounds(180, 310, 40, 30);

        b53.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b53ActionPerformed(evt);
            }
        });
        getContentPane().add(b53);
        b53.setBounds(80, 310, 70, 30);

        b55.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b55ActionPerformed(evt);
            }
        });
        getContentPane().add(b55);
        b55.setBounds(250, 310, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\j14165U.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b30ActionPerformed
       
        
//        TrainProblem ob1;
//            ob1=new TrainProblem(f,b,bn,tf10.getText(),tn);
//            ob1.setVisible(true);
//            this.dispose();
//            
            
        
        tf10.getText();
        String mob="select * from ps where Pmob1='"+tf10.getText()+"' OR Pmob2='"+tf10.getText()+"' and TrNo='"+tn+"'";
        try
        {
        mycon1.rs=mycon1.stm.executeQuery(mob);
        if(mycon1.rs.next())
        {
            this.dispose();
            TrainProblem ob1;
            ob1=new TrainProblem(f,b,bn,tf10.getText(),tn);
            ob1.setVisible(true);
            
        }
            }catch(Exception e)
        {
//            System.out.println(e);
        }
        
     // TODO add your handling code here:
    }//GEN-LAST:event_b30ActionPerformed

    private void b44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b44ActionPerformed
        tf10.setText(tf10.getText()+"1");
        // TODO add your handling code here:
    }//GEN-LAST:event_b44ActionPerformed

    private void b45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b45ActionPerformed
        tf10.setText(tf10.getText()+"2");        // TODO add your handling code here:
    }//GEN-LAST:event_b45ActionPerformed

    private void b46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b46ActionPerformed
        tf10.setText(tf10.getText()+"3");        // TODO add your handling code here:
    }//GEN-LAST:event_b46ActionPerformed

    private void b47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b47ActionPerformed
       tf10.setText(tf10.getText()+"4");        // TODO add your handling code here:
    }//GEN-LAST:event_b47ActionPerformed

    private void b48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b48ActionPerformed
       tf10.setText(tf10.getText()+"5");        // TODO add your handling code here:
    }//GEN-LAST:event_b48ActionPerformed

    private void b49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b49ActionPerformed
       tf10.setText(tf10.getText()+"6");        // TODO add your handling code here:
    }//GEN-LAST:event_b49ActionPerformed

    private void b50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b50ActionPerformed
       tf10.setText(tf10.getText()+"7");        // TODO add your handling code here:
    }//GEN-LAST:event_b50ActionPerformed

    private void b51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b51ActionPerformed
      tf10.setText(tf10.getText()+"8");        // TODO add your handling code here:
    }//GEN-LAST:event_b51ActionPerformed

    private void b52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b52ActionPerformed
      tf10.setText(tf10.getText()+"9");        // TODO add your handling code here:
    }//GEN-LAST:event_b52ActionPerformed

    private void b53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b53ActionPerformed
        tf10.setText(tf10.getText().substring(0,tf10.getText().length()-1));
        System.out.println(tf10.getText().length()-1);
// TODO add your handling code here:
    }//GEN-LAST:event_b53ActionPerformed

    private void b54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b54ActionPerformed
       tf10.setText(tf10.getText()+"0");        // TODO add your handling code here:
    }//GEN-LAST:event_b54ActionPerformed

    private void b55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b55ActionPerformed
        tf10.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_b55ActionPerformed

    private void tf10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf10ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b30;
    private javax.swing.JButton b44;
    private javax.swing.JButton b45;
    private javax.swing.JButton b46;
    private javax.swing.JButton b47;
    private javax.swing.JButton b48;
    private javax.swing.JButton b49;
    private javax.swing.JButton b50;
    private javax.swing.JButton b51;
    private javax.swing.JButton b52;
    private javax.swing.JButton b53;
    private javax.swing.JButton b54;
    private javax.swing.JButton b55;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l16;
    private javax.swing.JTextField tf10;
    // End of variables declaration//GEN-END:variables
private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("FLAG22.png")));
    }

}
