/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitparis.train.passenger;

import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import parabitparis.PbtDbConn;
import java.awt.Toolkit;
/**
 *
 * @author HP
 */
public class TrainCorruption extends javax.swing.JDialog {

    /**
     * Creates new form TrainCorruption
     */
    LocalTime lt;
    LocalDate ld;
    int c,v;
    PbtDbConn mycon1,mycon2,mycon3,mycon4;
    String bn,mob,bu1,bu2,bu3,bu5,prs,tn,reseid,se,bu6;
    public TrainCorruption(java.awt.Frame parent, boolean modal,String sr,String no,String mm,String set) {
        super(parent, modal);
        initComponents();
        setIconImage();
        this.setBounds(500,220,400,330);
        b75.setOpaque(false);
        b75.setContentAreaFilled(false);
        b75.setBorderPainted(false);
        b76.setOpaque(false);
        b76.setContentAreaFilled(false);
        b76.setBorderPainted(false);
        bn=sr;
        mob=no;
        tn=mm;
        se=set;
        mycon1=new PbtDbConn();
        mycon2=new PbtDbConn();
        mycon3=new PbtDbConn();
        mycon4=new PbtDbConn();
        ld=LocalDate.now();
        lt=LocalTime.now();
        
//         bu6="select a.EID from dutyreg a,emp b where b.Des='TC' and a.EID=b.EID and a.Rex LIKE(%'"+bn+"'%)";
//        mycon1.rs=mycon1.stm.executeQuery(bu6);
//        if(mycon1.rs.next()==true)
//        {
//        
//        }
       /* bu3="select MAX(CompNo) from rtproblem";
        try
        {
        mycon1.rs=mycon1.stm.executeQuery(bu3);
        if(mycon1.rs.next()){
            v=mycon1.rs.getInt("MAX(CompNo)");
        }
        }catch(Exception e)
        {System.out.println(e);}*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b75 = new javax.swing.JButton();
        b76 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        b75.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b75.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\comb\\traincoru\\TC1.jpg")); // NOI18N
        b75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b75ActionPerformed(evt);
            }
        });
        getContentPane().add(b75);
        b75.setBounds(40, 100, 140, 90);

        b76.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b76.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\buttons\\edit\\comb\\traincoru\\SECURITY11.jpg")); // NOI18N
        b76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b76ActionPerformed(evt);
            }
        });
        getContentPane().add(b76);
        b76.setBounds(200, 100, 150, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ParabitPARIS\\assects\\gradi\\new.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b75ActionPerformed
          ld= LocalDate.now();
        lt= LocalTime.now();
        
        bu5="select PrevSID from currentstatus where TrNo='"+tn+"'";
        try{
        mycon3.rs=mycon3.stm.executeQuery(bu5);
        if(mycon3.rs.next())
        {
            prs=mycon3.rs.getString("PrevSID");
        }
                }catch(Exception e){
                    System.out.println(e);
                }
        String bu6="select PNR,Count from rtproblem where Coach='"+bn+"' and PrID='PR 1'";
        try
        {
        mycon4.rs=mycon4.stm.executeQuery(bu6);
        if(mycon4.rs.next())
        {   mycon4.rs.getString("PNR");
            int w=mycon4.rs.getInt("Count");
            if(mycon4.rs.getString("PNR")!=bu1){
                w=w+1;
            
            String re="update rtproblem set Count='"+w+"' where Coach='"+bn+"' and PrID='PR 1'";
                mycon4.stm.executeUpdate(re);
            }
           
        }
        else
        {
            if(mycon4.rs.next()&&mycon4.rs.getString("PNR").equals(bu1)){
            JOptionPane.showMessageDialog(null, "ALREADY REGISTERED");
            }else{
                 JOptionPane.showMessageDialog(null,"DONE");
            String su="insert into rtproblem values('0','PR 1','"+bu2+"','"+ld+"','"+lt+"','"+bn+"',"+se+",'"+mob+"',"+reseid+",'N',"+prs+",null,null,null,1)";
      System.out.println(su);
            c=mycon1.stm.executeUpdate(su);
       System.out.println(c);
        }}
        }catch(Exception e)
        {
        e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_b75ActionPerformed

    private void b76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b76ActionPerformed
         ld= LocalDate.now();
        lt= LocalTime.now();
        
        bu5="select PrevSID from currentstatus where TrNo='"+tn+"'";
        try{
        mycon3.rs=mycon3.stm.executeQuery(bu5);
        if(mycon3.rs.next())
        {
            prs=mycon3.rs.getString("PrevSID");
        }
                }catch(Exception e){
                    e.printStackTrace();
                }
        String bu6="select PNR,Count from rtproblem where Coach='"+bn+"' and PrID='PR 2'";
        try
        {
        mycon4.rs=mycon4.stm.executeQuery(bu6);
        if(mycon4.rs.next())
        {   mycon4.rs.getString("PNR");
            int w=mycon4.rs.getInt("Count");
           if(mycon4.rs.getString("PNR")!=bu1){
            w=w+1;
            String re="update rtproblem set Count='"+w+"' where Coach='"+bn+"' and PrID='PR 2'";
                mycon4.stm.executeUpdate(re);
           }
           
        }
        else
        {
            if(mycon4.rs.next()&&mycon4.rs.getString("PNR").equals(bu1)){
            JOptionPane.showMessageDialog(null, "ALREADY REGISTERED");
            }else{
                JOptionPane.showMessageDialog(null,"DONE");
            String su="insert into rtproblem values(null,'PR 2','"+bu2+"','"+ld+"','"+lt+"','"+bn+"',"+se+",'"+mob+"',"+reseid+",'N',"+prs+",null,null,null,1)";
      System.out.println(su);
            c=mycon1.stm.executeUpdate(su);
       System.out.println(c);
        }}
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_b76ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b75;
    private javax.swing.JButton b76;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("FLAG22.png")));
    }

}
